//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Adjustment_Header
    {
        public long Adjustmentd { get; set; }
        public byte CompanyId { get; set; }
        public short LocationId { get; set; }
        public System.DateTime AdjustmentDateTime { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public Nullable<short> CancelBy { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string AdjustmentNo { get; set; }
    
        public virtual CL_Master_Company CL_Master_Company { get; set; }
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        public virtual CL_Master_User CL_Master_User { get; set; }
    }
}
