//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Adjustment_Detail
    {
        public long AdjustmentId { get; set; }
        public long BillId { get; set; }
        public decimal AdjustmentAmount { get; set; }
        public bool IsCustomerBill { get; set; }
    }
}
