//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Account_Transaction
    {
        public long VoucherId { get; set; }
        public short AccountId { get; set; }
        public decimal DebitAmount { get; set; }
        public decimal CreditAmount { get; set; }
        public string Narration { get; set; }
        public byte TransactionType { get; set; }
        public short OppositeAccountId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public long SrNo { get; set; }
        public string DocumentNo { get; set; }
        public string Remarks { get; set; }
    
        public virtual CL_Master_Account CL_Master_Account { get; set; }
        public virtual CL_Master_Account CL_Master_Account1 { get; set; }
    }
}
