//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_Automail_Fail
    {
        public short MailId { get; set; }
        public Nullable<short> EventId { get; set; }
        public Nullable<short> DocumentType { get; set; }
        public Nullable<short> DocumentId { get; set; }
        public string MailTo { get; set; }
        public string MailCC { get; set; }
        public string MailBCC { get; set; }
        public string MailSubject { get; set; }
        public string MailBody { get; set; }
        public Nullable<bool> SentStatus { get; set; }
        public Nullable<byte> Attempt { get; set; }
        public Nullable<short> EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> FailDate { get; set; }
        public string FailErrorMessage { get; set; }
    }
}
