//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Advice
    {
        public long AdviceId { get; set; }
        public string AdviceNo { get; set; }
        public System.DateTime AdviceDate { get; set; }
        public byte AdviceType { get; set; }
        public short LocationId { get; set; }
        public short RaisedLocationId { get; set; }
        public byte AdviceStatus { get; set; }
        public decimal Amount { get; set; }
        public string Reason { get; set; }
        public string DocumentName { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public byte PaymentModeId { get; set; }
        public short FromAccountId { get; set; }
        public short ToAccountId { get; set; }
        public short RaisedAccountId { get; set; }
        public bool IsApprove { get; set; }
        public Nullable<short> ApproveBy { get; set; }
        public Nullable<short> ApproveLocationId { get; set; }
        public decimal ApproveAmount { get; set; }
        public byte CompanyId { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public long VoucherId { get; set; }
        public Nullable<System.DateTime> AcknowledgementDate { get; set; }
        public Nullable<long> AcknowledgementVoucherId { get; set; }
        public Nullable<short> AcknowledgementBy { get; set; }
    
        public virtual CL_Master_Company CL_Master_Company { get; set; }
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        public virtual CL_Master_Location CL_Master_Location1 { get; set; }
    }
}
