//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_CreditDebit_Header
    {
        public long CreditDebitId { get; set; }
        public string BillNo { get; set; }
        public string ManualBillNo { get; set; }
        public string ForBillNo { get; set; }
        public string BillType { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<long> VendorId { get; set; }
        public Nullable<long> ForBillId { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<short> LocationId { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
