//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_CreditDebitNote_Header
    {
        public long CreditDebitNoteId { get; set; }
        public string CreditDebitNoteNo { get; set; }
        public byte CreditDebitNoteType { get; set; }
        public byte CompanyId { get; set; }
        public System.DateTime CreditDebitNoteDate { get; set; }
        public short LocationId { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<byte> PartyTypeId { get; set; }
        public short PartyId { get; set; }
        public Nullable<short> BillTypeId { get; set; }
        public Nullable<short> AccountId { get; set; }
        public Nullable<bool> IsGst { get; set; }
        public string FinYear { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<short> CancelBy { get; set; }
        public string CancelReason { get; set; }
        public Nullable<decimal> TotalCreditDebitNoteAmount { get; set; }
    
        public virtual Cl_CreditDebitNote_Header Cl_CreditDebitNote_Header1 { get; set; }
        public virtual Cl_CreditDebitNote_Header Cl_CreditDebitNote_Header2 { get; set; }
    }
}
