//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_CustomerBill_Tax_Detail
    {
        public long BillId { get; set; }
        public byte TaxCode { get; set; }
        public decimal TaxPercentage { get; set; }
        public decimal TaxAmount { get; set; }
        public Nullable<long> DocketId { get; set; }
        public string DocketSuffix { get; set; }
    
        public virtual CL_CustomerBill_Header CL_CustomerBill_Header { get; set; }
    }
}
