//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_CustomerBill_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_CustomerBill_Header()
        {
            this.CL_CustomerBill_Detail = new HashSet<CL_CustomerBill_Detail>();
            this.CL_CustomerBill_Supplementry_Detail = new HashSet<CL_CustomerBill_Supplementry_Detail>();
            this.CL_CustomerBill_Tax_Detail = new HashSet<CL_CustomerBill_Tax_Detail>();
            this.CL_CustomerBill_Tripsheet_Detail = new HashSet<CL_CustomerBill_Tripsheet_Detail>();
            this.CL_Mr_Bill_Detail = new HashSet<CL_Mr_Bill_Detail>();
        }
    
        public long BillId { get; set; }
        public string BillNo { get; set; }
        public string ManualBillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public System.TimeSpan BillTime { get; set; }
        public Nullable<System.DateTime> BillDateTime { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.TimeSpan DueTime { get; set; }
        public Nullable<System.DateTime> DueDateTime { get; set; }
        public short GenerateLocationId { get; set; }
        public short GenerateUserId { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public Nullable<System.TimeSpan> SubmissionTime { get; set; }
        public Nullable<System.DateTime> SubmissionDateTime { get; set; }
        public short SubmissionLocationId { get; set; }
        public short SubmissionUserId { get; set; }
        public Nullable<System.DateTime> CollectionDate { get; set; }
        public Nullable<System.TimeSpan> CollectionTime { get; set; }
        public Nullable<System.DateTime> CollectionDateTime { get; set; }
        public Nullable<short> CollectionLocationId { get; set; }
        public Nullable<short> CollectionUserId { get; set; }
        public string SubmittedTo { get; set; }
        public string SubmittedContactNo { get; set; }
        public byte PaybasId { get; set; }
        public short CustomerId { get; set; }
        public decimal BillAmount { get; set; }
        public byte BillStatus { get; set; }
        public bool IsFinalized { get; set; }
        public bool IsCancelled { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public string CancelledReason { get; set; }
        public Nullable<short> CancelBy { get; set; }
        public Nullable<System.DateTime> FinalizeDate { get; set; }
        public Nullable<short> FinalizeBy { get; set; }
        public decimal TaxPercentageTotal { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TaxTotal { get; set; }
        public decimal PendingAmount { get; set; }
        public Nullable<byte> GstSacId { get; set; }
        public Nullable<byte> GstServiceTypeId { get; set; }
        public Nullable<long> CompanyGstId { get; set; }
        public Nullable<long> PartyGstId { get; set; }
        public string Remarks { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public byte CompanyId { get; set; }
        public Nullable<byte> TransportModeId { get; set; }
        public Nullable<byte> ServiceTypeId { get; set; }
        public Nullable<byte> FtlTypeId { get; set; }
        public Nullable<short> SubmittedByUserId { get; set; }
        public string SubmittedDocumentName { get; set; }
        public Nullable<bool> IsGSTBasedOnBillState { get; set; }
        public Nullable<long> TripsheetBillId { get; set; }
        public Nullable<long> MilkRunsheetBillId { get; set; }
        public string CustomerGstStateGstTinNo { get; set; }
        public Nullable<long> ManifestId { get; set; }
        public Nullable<bool> isCreditDebitNote { get; set; }
        public Nullable<short> VendorId { get; set; }
        public Nullable<long> addressid { get; set; }
        public Nullable<short> CustomerAddressId { get; set; }
        public string BillSubmissionRemarks { get; set; }
        public string BillFinalizationRemarks { get; set; }
        public string BillCollectionRemarks { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public string Irn { get; set; }
        public string SignedQRCode { get; set; }
        public string SignedInvoice { get; set; }
        public string IrnStatus { get; set; }
        public bool IsSez { get; set; }
        public bool IsRCM { get; set; }
        public string AckNo { get; set; }
        public Nullable<short> VehicleId { get; set; }
        public Nullable<byte> TransactionTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CustomerBill_Detail> CL_CustomerBill_Detail { get; set; }
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        public virtual CL_Master_User CL_Master_User { get; set; }
        public virtual CL_Master_Company CL_Master_Company { get; set; }
        public virtual CL_Master_Customer CL_Master_Customer { get; set; }
        public virtual CL_Master_Location CL_Master_Location1 { get; set; }
        public virtual CL_Master_User CL_Master_User1 { get; set; }
        public virtual CL_Master_Location CL_Master_Location2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CustomerBill_Supplementry_Detail> CL_CustomerBill_Supplementry_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CustomerBill_Tax_Detail> CL_CustomerBill_Tax_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CustomerBill_Tripsheet_Detail> CL_CustomerBill_Tripsheet_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Mr_Bill_Detail> CL_Mr_Bill_Detail { get; set; }
    }
}
