//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_CustomerBill_Tripsheet_Detail
    {
        public long BillId { get; set; }
        public long TripsheetId { get; set; }
        public decimal AcKm { get; set; }
        public decimal NonAcKm { get; set; }
        public decimal EmptyKm { get; set; }
        public decimal FixedAcRate { get; set; }
        public decimal FixedNonAcRate { get; set; }
        public decimal FixedEmptyRate { get; set; }
        public decimal VariableAcRate { get; set; }
        public decimal VariableNonAcRate { get; set; }
        public decimal VariableEmptyRate { get; set; }
        public decimal GrossAmount { get; set; }
        public decimal GstAmount { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual CL_CustomerBill_Header CL_CustomerBill_Header { get; set; }
        public virtual CL_Tripsheet_Header CL_Tripsheet_Header { get; set; }
    }
}
