//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_CreditDebitNote_Detail
    {
        public long CreditDebitNoteId { get; set; }
        public long BillId { get; set; }
        public Nullable<byte> TransportModeId { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public decimal CreditDebitNoteAmount { get; set; }
        public Nullable<decimal> SubAmount { get; set; }
        public Nullable<decimal> GstRate { get; set; }
        public Nullable<decimal> IGst { get; set; }
        public Nullable<decimal> SGst { get; set; }
        public Nullable<decimal> CGst { get; set; }
        public Nullable<decimal> UGst { get; set; }
        public Nullable<decimal> GstAmount { get; set; }
        public string CreditDebitNotePurposeId { get; set; }
        public string Remarks { get; set; }
    }
}
