//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_CustomerBill_Submission_Header
    {
        public long SubmissionId { get; set; }
        public string SubmissionNo { get; set; }
        public Nullable<System.DateTime> SubmissionDateTime { get; set; }
        public Nullable<short> SubmissionUserId { get; set; }
        public string SubmittedTo { get; set; }
        public short CustomerId { get; set; }
        public short SubmissionLocationId { get; set; }
        public Nullable<byte> CompanyId { get; set; }
        public string SubmissionRemarks { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public Nullable<short> CancelBy { get; set; }
    }
}
