//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_CreditDebitNote_TaxDetail
    {
        public long NoteId { get; set; }
        public long TaxCode { get; set; }
        public decimal TaxAmount { get; set; }
    }
}
