//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_CreditDebit_TaxDetail
    {
        public long CreditDebitId { get; set; }
        public string TaxCode { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
    }
}
