//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_CustomerBill_Header_Log
    {
        public long HistoryBillId { get; set; }
        public Nullable<long> BillId { get; set; }
        public string BillNo { get; set; }
        public string ManualBillNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<System.TimeSpan> BillTime { get; set; }
        public Nullable<System.DateTime> BillDateTime { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.TimeSpan> DueTime { get; set; }
        public Nullable<System.DateTime> DueDateTime { get; set; }
        public Nullable<short> GenerateLocationId { get; set; }
        public Nullable<short> GenerateUserId { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public Nullable<System.TimeSpan> SubmissionTime { get; set; }
        public Nullable<System.DateTime> SubmissionDateTime { get; set; }
        public Nullable<short> SubmissionLocationId { get; set; }
        public Nullable<short> SubmissionUserId { get; set; }
        public Nullable<System.DateTime> CollectionDate { get; set; }
        public Nullable<System.TimeSpan> CollectionTime { get; set; }
        public Nullable<System.DateTime> CollectionDateTime { get; set; }
        public Nullable<short> CollectionLocationId { get; set; }
        public Nullable<short> CollectionUserId { get; set; }
        public string SubmittedTo { get; set; }
        public string SubmittedContactNo { get; set; }
        public Nullable<byte> PaybasId { get; set; }
        public Nullable<short> CustomerId { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public Nullable<byte> BillStatus { get; set; }
        public Nullable<bool> IsFinalized { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public string CancelledReason { get; set; }
        public Nullable<short> CancelBy { get; set; }
        public Nullable<System.DateTime> FinalizeDate { get; set; }
        public Nullable<short> FinalizeBy { get; set; }
        public Nullable<decimal> TaxPercentageTotal { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> TaxTotal { get; set; }
        public Nullable<decimal> PendingAmount { get; set; }
        public Nullable<byte> GstSacId { get; set; }
        public Nullable<byte> GstServiceTypeId { get; set; }
        public Nullable<long> CompanyGstId { get; set; }
        public Nullable<long> PartyGstId { get; set; }
        public string Remarks { get; set; }
        public Nullable<short> EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<byte> CompanyId { get; set; }
        public Nullable<byte> TransportModeId { get; set; }
        public Nullable<byte> ServiceTypeId { get; set; }
        public Nullable<byte> FtlTypeId { get; set; }
        public Nullable<short> SubmittedByUserId { get; set; }
        public string SubmittedDocumentName { get; set; }
        public Nullable<bool> IsGSTBasedOnBillState { get; set; }
        public Nullable<long> TripsheetBillId { get; set; }
        public Nullable<long> MilkRunsheetBillId { get; set; }
        public string CustomerGstStateGstTinNo { get; set; }
        public Nullable<long> ManifestId { get; set; }
        public Nullable<bool> isCreditDebitNote { get; set; }
        public Nullable<short> VendorId { get; set; }
        public Nullable<long> addressid { get; set; }
        public Nullable<short> CustomerAddressId { get; set; }
    }
}
