//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Cheque_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Cheque_Detail()
        {
            this.CL_Mr_Header = new HashSet<CL_Mr_Header>();
        }
    
        public long ChequeId { get; set; }
        public string ChequeNo { get; set; }
        public System.DateTime ChequeDate { get; set; }
        public short BankId { get; set; }
        public decimal ChequeAmount { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public byte CompanyId { get; set; }
        public short LocationId { get; set; }
        public bool IsDeposited { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public byte ChequeStatus { get; set; }
        public Nullable<short> DepositBy { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> DepositVoucherId { get; set; }
        public bool IsOnAccount { get; set; }
        public decimal CollectionAmount { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public bool ChequeType { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public Nullable<System.DateTime> ChequeClearDate { get; set; }
        public string ChequeClearRemarks { get; set; }
        public Nullable<System.DateTime> ReconciledDate { get; set; }
        public Nullable<short> ReconciledBy { get; set; }
        public bool IsReconciled { get; set; }
        public Nullable<byte> PartyTypeId { get; set; }
        public Nullable<short> PartyId { get; set; }
        public Nullable<short> CancelBy { get; set; }
    
        public virtual CL_Master_Account CL_Master_Account { get; set; }
        public virtual CL_Master_Company CL_Master_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Mr_Header> CL_Mr_Header { get; set; }
    }
}
