//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_CustomerBill_Detail_Log
    {
        public long HistoryBillId { get; set; }
        public long BillId { get; set; }
        public long DocketId { get; set; }
        public string DocketSuffix { get; set; }
    }
}
