//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Docket_Detail_History
    {
        public long HistoryId { get; set; }
        public long DocketId { get; set; }
        public string Remarks { get; set; }
        public Nullable<byte> PickupDeliveryTypeId { get; set; }
        public Nullable<byte> LoadTypeId { get; set; }
        public Nullable<byte> IndustryId { get; set; }
        public Nullable<byte> DivisionId { get; set; }
        public Nullable<bool> IsLocal { get; set; }
        public Nullable<bool> IsOda { get; set; }
        public Nullable<bool> IsDeferment { get; set; }
        public Nullable<bool> IsVolumetric { get; set; }
        public Nullable<bool> IsCod { get; set; }
        public Nullable<bool> IsDacc { get; set; }
        public Nullable<bool> IsPermit { get; set; }
        public Nullable<bool> IsMultiPickup { get; set; }
        public Nullable<bool> IsMultiDelivery { get; set; }
        public Nullable<long> MotherDocketId { get; set; }
        public Nullable<bool> IsCarrierRisk { get; set; }
        public string PolicyNo { get; set; }
        public Nullable<System.DateTime> PolicyDate { get; set; }
        public Nullable<decimal> ModvatCovers { get; set; }
        public Nullable<decimal> InternalCovers { get; set; }
        public Nullable<System.DateTime> CustomerReferenceDate { get; set; }
        public string CustomerGatepassNo { get; set; }
        public string CustomerDeliveryNo { get; set; }
        public string PrivateMark { get; set; }
        public string TPNo { get; set; }
        public string EntrysheetNo { get; set; }
        public string ObdNo { get; set; }
        public string EngineNo { get; set; }
        public string ModelNo { get; set; }
        public string GpsNo { get; set; }
        public string ChassisNo { get; set; }
        public Nullable<byte> PermitReceivedAt { get; set; }
        public string PermitNo { get; set; }
        public Nullable<System.DateTime> PermitDate { get; set; }
        public Nullable<System.DateTime> PermitValidityDate { get; set; }
        public Nullable<System.DateTime> PermitReceivedDate { get; set; }
        public Nullable<decimal> CftRatio { get; set; }
        public string ServiceTaxRegisterNo { get; set; }
        public string LocalServiceTaxRegisterNo { get; set; }
        public Nullable<short> ConsignorId { get; set; }
        public string ConsignorName { get; set; }
        public Nullable<short> ConsignorAddressId { get; set; }
        public string ConsignorAddress1 { get; set; }
        public string ConsignorAddress2 { get; set; }
        public Nullable<short> ConsignorCityId { get; set; }
        public string ConsignorPincode { get; set; }
        public string ConsignorMobileNo { get; set; }
        public string ConsignorEmailId { get; set; }
        public string ConsignorGstTinNo { get; set; }
        public Nullable<short> ConsigneeId { get; set; }
        public string ConsigneeName { get; set; }
        public Nullable<short> ConsigneeAddressId { get; set; }
        public string ConsigneeAddress1 { get; set; }
        public string ConsigneeAddress2 { get; set; }
        public Nullable<short> ConsigneeCityId { get; set; }
        public string ConsigneePincode { get; set; }
        public string ConsigneeMobileNo { get; set; }
        public string ConsigneeEmailId { get; set; }
        public string ConsigneeGstTinNo { get; set; }
        public string VehicleNo { get; set; }
        public Nullable<bool> IsPodUploaded { get; set; }
        public Nullable<System.DateTime> DocketDateTime { get; set; }
        public Nullable<bool> IsPodForward { get; set; }
        public Nullable<short> PfmLocationId { get; set; }
        public string TplNo { get; set; }
        public string TplReason { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsBookedByBa { get; set; }
        public Nullable<short> BookedById { get; set; }
        public Nullable<bool> IsPickupThroughSameVehicle { get; set; }
        public Nullable<bool> IsDeliveryThroughSameVehicle { get; set; }
        public Nullable<short> VendorTypeId { get; set; }
        public Nullable<decimal> TotalCubic { get; set; }
        public Nullable<bool> IsPartVolumetric { get; set; }
    
        public virtual CL_Docket_History CL_Docket_History { get; set; }
    }
}
