//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_DCR_Management_History
    {
        public long Id { get; set; }
        public string Action { get; set; }
        public short ActionBy { get; set; }
        public System.DateTime ActionDate { get; set; }
    
        public virtual CL_DCR CL_DCR { get; set; }
    }
}
