//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Docket_Charge_Detail_BillHistory
    {
        public int ID { get; set; }
        public long DocketId { get; set; }
        public byte ChargeCode { get; set; }
        public byte ChargeRateTypeId { get; set; }
        public decimal ChargeAmount { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TaxTotal { get; set; }
        public decimal GrandTotal { get; set; }
        public Nullable<System.DateTime> EntryDateTime { get; set; }
        public Nullable<long> PartyGstId { get; set; }
        public Nullable<short> GstStateId { get; set; }
        public string GstinNo { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> UGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
    }
}
