//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Docket_Charge_ReInvoke_History
    {
        public long SrNo { get; set; }
        public Nullable<long> DocketId { get; set; }
        public Nullable<short> ContractCustomerId { get; set; }
        public Nullable<short> ContractId { get; set; }
        public Nullable<byte> ProductTypeId { get; set; }
        public Nullable<byte> PackagingTypeId { get; set; }
        public Nullable<byte> FtlTypeId { get; set; }
        public Nullable<byte> RateTypeId { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> FreightRate { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> TaxTotal { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<bool> IsBilled { get; set; }
        public Nullable<decimal> TaxPercentageTotal { get; set; }
        public Nullable<bool> IsFinalize { get; set; }
        public Nullable<System.DateTime> FinalizeDate { get; set; }
        public string DeclarationFileName { get; set; }
        public Nullable<byte> GstSacId { get; set; }
        public Nullable<byte> GstServiceTypeId { get; set; }
        public string GstTinNo { get; set; }
        public Nullable<bool> IsInterState { get; set; }
        public Nullable<bool> IsRcm { get; set; }
        public Nullable<decimal> GstAmount { get; set; }
        public Nullable<bool> IsBillingPartyGstPayer { get; set; }
        public string CompanyGstTinNo { get; set; }
        public Nullable<long> CompanyGstId { get; set; }
        public Nullable<long> PartyGstId { get; set; }
        public Nullable<decimal> VendorFreight { get; set; }
        public Nullable<decimal> VendorFreightRate { get; set; }
        public Nullable<byte> VendorRateTypeId { get; set; }
        public Nullable<short> VendorId { get; set; }
        public Nullable<short> VendorContractId { get; set; }
        public Nullable<decimal> VendorSubTotal { get; set; }
        public Nullable<decimal> VendorTaxTotal { get; set; }
        public Nullable<decimal> VendorGrandTotal { get; set; }
        public Nullable<decimal> VendorGstAmount { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public Nullable<long> AdvanceVoucherId { get; set; }
        public Nullable<bool> IsBaDoorPickup { get; set; }
        public Nullable<bool> IsBaDoorDelivery { get; set; }
        public Nullable<decimal> BookingKartAmount { get; set; }
        public Nullable<bool> IsBulky { get; set; }
        public Nullable<decimal> BulkyAmount { get; set; }
        public Nullable<decimal> DeliveryKartAmount { get; set; }
        public Nullable<short> BookingKartBaId { get; set; }
        public Nullable<short> DeliveryKartBaId { get; set; }
        public Nullable<byte> GstPaidById { get; set; }
        public Nullable<short> FreightContractId { get; set; }
        public Nullable<short> GstStateId { get; set; }
    }
}
