//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_DCR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_DCR()
        {
            this.CL_DCR_Management_History = new HashSet<CL_DCR_Management_History>();
            this.CL_Document_Void = new HashSet<CL_Document_Void>();
        }
    
        public long Id { get; set; }
        public byte DocumentTypeId { get; set; }
        public string BookCode { get; set; }
        public byte BusinessTypeId { get; set; }
        public string SeriesFrom { get; set; }
        public string SeriesTo { get; set; }
        public short LocationId { get; set; }
        public string AllotedCategory { get; set; }
        public Nullable<short> AllotedTo { get; set; }
        public decimal Total { get; set; }
        public decimal Used { get; set; }
        public decimal Cancelled { get; set; }
        public decimal Void { get; set; }
        public string Suffix { get; set; }
        public string SuffixBase { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public System.DateTime AllotedDate { get; set; }
        public Nullable<byte> CompanyId { get; set; }
        public Nullable<bool> IsComputerized { get; set; }
    
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_DCR_Management_History> CL_DCR_Management_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Document_Void> CL_Document_Void { get; set; }
    }
}
