//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Docket_Dispatch_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Docket_Dispatch_Header()
        {
            this.CL_Docket_Summary = new HashSet<CL_Docket_Summary>();
        }
    
        public long DispatchId { get; set; }
        public string DispatchNo { get; set; }
        public System.DateTime DispatchDateTime { get; set; }
        public short VehicleId { get; set; }
        public short FromLocationId { get; set; }
        public short ToLocationId { get; set; }
        public short DriverId { get; set; }
        public short RouteId { get; set; }
        public string ReferenceNo { get; set; }
        public short AccountId { get; set; }
        public short DestinationLocationId { get; set; }
        public string Remarks { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
        public int NetPackages { get; set; }
        public decimal ToPay { get; set; }
        public decimal TruckFreight { get; set; }
        public int DisplayPackages { get; set; }
        public decimal DeliveryCommission { get; set; }
        public decimal AdvanceFreight { get; set; }
        public decimal ActualWeight { get; set; }
        public decimal DoCharge { get; set; }
        public decimal LabourCharges { get; set; }
        public decimal ChargedWeight { get; set; }
        public decimal KatAmount { get; set; }
        public decimal TotalPaidAmount { get; set; }
        public decimal BalanceFreight { get; set; }
        public decimal PrintFreight { get; set; }
        public decimal Pf { get; set; }
        public decimal UnloadingCharge { get; set; }
        public decimal NetFreight { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<short> CancelBy { get; set; }
        public string CancelReason { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public byte CompanyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Docket_Summary> CL_Docket_Summary { get; set; }
    }
}
