//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Drs_Detail_History
    {
        public long HistoryId { get; set; }
        public Nullable<long> DrsId { get; set; }
        public Nullable<long> DocketId { get; set; }
        public string DocketSuffix { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.TimeSpan> DeliveryTime { get; set; }
        public Nullable<System.DateTime> DeliveryDateTime { get; set; }
        public Nullable<int> ArrivedPackages { get; set; }
        public Nullable<int> DeliveredPackages { get; set; }
        public string DeliveryPersonName { get; set; }
        public Nullable<byte> PartDeliveryReasonId { get; set; }
        public Nullable<byte> LateDeliveryReasonId { get; set; }
        public Nullable<byte> UndeliveredReasonId { get; set; }
        public string Remark { get; set; }
    
        public virtual CL_Drs_Header_History CL_Drs_Header_History { get; set; }
    }
}
