//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Deps_Header
    {
        public long DepsId { get; set; }
        public string DepsNo { get; set; }
        public short LocationId { get; set; }
        public System.DateTime DepsDate { get; set; }
        public System.TimeSpan DepsTime { get; set; }
        public Nullable<System.DateTime> DepsDateTime { get; set; }
        public byte DepsType { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<short> CancelBy { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public long ThcId { get; set; }
    }
}
