//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Docket_Charge_Detail
    {
        public long DocketId { get; set; }
        public byte ChargeCode { get; set; }
        public byte ChargeRateTypeId { get; set; }
        public decimal ChargeAmount { get; set; }
    
        public virtual CL_Docket CL_Docket { get; set; }
    }
}
