//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Docket_Invoice_Part_History
    {
        public long HistoryId { get; set; }
        public long DocketId { get; set; }
        public long InvoiceId { get; set; }
        public int PartId { get; set; }
        public string PartName { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> PartAmount { get; set; }
        public Nullable<bool> IsCod { get; set; }
        public Nullable<short> PackingTypeId { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<int> Packages { get; set; }
        public Nullable<decimal> PartVolumetricWeight { get; set; }
        public Nullable<decimal> PartActualWeight { get; set; }
        public Nullable<decimal> PartChargedWeight { get; set; }
    
        public virtual CL_Docket_History CL_Docket_History { get; set; }
    }
}
