//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Docket_Document_History
    {
        public long HistoryId { get; set; }
        public long DocketId { get; set; }
        public long StateDocumentId { get; set; }
        public string DocumentNo { get; set; }
    
        public virtual CL_Docket_History CL_Docket_History { get; set; }
    }
}
