//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Docket_HoldUnhold
    {
        public long HoldId { get; set; }
        public long DocketId { get; set; }
        public short HoldLocationId { get; set; }
        public string HoldReason { get; set; }
        public short HoldBy { get; set; }
        public System.DateTime HoldDate { get; set; }
        public Nullable<short> UnholdLocationId { get; set; }
        public string UnholdReason { get; set; }
        public Nullable<short> UnholdBy { get; set; }
        public Nullable<System.DateTime> UnholdDate { get; set; }
        public bool IsCancel { get; set; }
        public byte CompanyId { get; set; }
    }
}
