//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Docket_BookingChallan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Docket_BookingChallan()
        {
            this.CL_Docket_BookingChallan_Detail = new HashSet<CL_Docket_BookingChallan_Detail>();
        }
    
        public long ChallanId { get; set; }
        public string ChallanNo { get; set; }
        public string ManualChallanNo { get; set; }
        public short VendorId { get; set; }
        public System.DateTime ChallanDate { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Docket_BookingChallan_Detail> CL_Docket_BookingChallan_Detail { get; set; }
        public virtual CL_Master_Vendor CL_Master_Vendor { get; set; }
    }
}
