//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Drs_Detail
    {
        public long DrsId { get; set; }
        public long DocketId { get; set; }
        public string DocketSuffix { get; set; }
        public bool IsDelivered { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.TimeSpan> DeliveryTime { get; set; }
        public string DeliveryDateTime { get; set; }
        public int ArrivedPackages { get; set; }
        public int DeliveredPackages { get; set; }
        public string DeliveryPersonName { get; set; }
        public Nullable<byte> PartDeliveryReasonId { get; set; }
        public Nullable<byte> LateDeliveryReasonId { get; set; }
        public Nullable<byte> UndeliveredReasonId { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> isLabourBill { get; set; }
        public Nullable<decimal> LabourAmount { get; set; }
    }
}
