//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Docket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Docket()
        {
            this.CL_CustomerBill_Detail = new HashSet<CL_CustomerBill_Detail>();
            this.CL_Docket_Charge_Detail = new HashSet<CL_Docket_Charge_Detail>();
            this.CL_Docket_Document = new HashSet<CL_Docket_Document>();
            this.CL_Docket_Invoice = new HashSet<CL_Docket_Invoice>();
            this.CL_Docket_Summary = new HashSet<CL_Docket_Summary>();
            this.CL_Docket_Tax_Detail = new HashSet<CL_Docket_Tax_Detail>();
            this.CL_Mr_Header = new HashSet<CL_Mr_Header>();
            this.CL_Prs_Header = new HashSet<CL_Prs_Header>();
            this.CL_Tripsheet_Header = new HashSet<CL_Tripsheet_Header>();
        }
    
        public long DocketId { get; set; }
        public string DocketNo { get; set; }
        public System.DateTime DocketDate { get; set; }
        public short FromLocationId { get; set; }
        public short ToLocationId { get; set; }
        public Nullable<int> FromCityId { get; set; }
        public Nullable<int> ToCityId { get; set; }
        public byte TransportModeId { get; set; }
        public byte PaybasId { get; set; }
        public System.DateTime Edd { get; set; }
        public int Packages { get; set; }
        public decimal ActualWeight { get; set; }
        public decimal ChargedWeight { get; set; }
        public byte BusinessTypeId { get; set; }
        public byte ServiceTypeId { get; set; }
        public short BillLocationId { get; set; }
        public string CustomerReferenceNo { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public bool IsCancel { get; set; }
        public byte CompanyId { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public Nullable<short> CancelBy { get; set; }
        public Nullable<bool> IsTpl { get; set; }
        public string CustomerDocketNo { get; set; }
        public Nullable<bool> IsOld { get; set; }
        public string DocketType { get; set; }
        public Nullable<bool> isBABilled { get; set; }
        public Nullable<long> StatusId { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<bool> isBADeliveryBilled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CustomerBill_Detail> CL_CustomerBill_Detail { get; set; }
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        public virtual CL_Docket_Charge CL_Docket_Charge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Docket_Charge_Detail> CL_Docket_Charge_Detail { get; set; }
        public virtual CL_Docket_Detail CL_Docket_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Docket_Document> CL_Docket_Document { get; set; }
        public virtual CL_Master_Location CL_Master_Location1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Docket_Invoice> CL_Docket_Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Docket_Summary> CL_Docket_Summary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Docket_Tax_Detail> CL_Docket_Tax_Detail { get; set; }
        public virtual CL_Master_Location CL_Master_Location2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Mr_Header> CL_Mr_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Prs_Header> CL_Prs_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Tripsheet_Header> CL_Tripsheet_Header { get; set; }
    }
}
