//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Docket_Charge_Detail_ReInvoke_History
    {
        public long SrNo { get; set; }
        public Nullable<long> DocketId { get; set; }
        public Nullable<byte> ChargeCode { get; set; }
        public Nullable<byte> ChargeRateTypeId { get; set; }
        public Nullable<decimal> ChargeAmount { get; set; }
    }
}
