//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Docket_Summary_History
    {
        public long HistoryId { get; set; }
        public long DocketId { get; set; }
        public string DocketSuffix { get; set; }
        public short ToLocationId { get; set; }
        public int Packages { get; set; }
        public decimal ActualWeight { get; set; }
        public Nullable<decimal> ChargedWeight { get; set; }
        public bool LoadingSheetStatus { get; set; }
        public bool ManifestStatus { get; set; }
        public bool PrsStatus { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public bool IsDelivered { get; set; }
        public int ArrivalPackages { get; set; }
        public int DeliveredPackages { get; set; }
        public bool UnderDrs { get; set; }
        public short CurrentLocationId { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public string DocketStatus { get; set; }
        public string StockType { get; set; }
        public decimal ArrivalWeight { get; set; }
        public string DeliveryPersonName { get; set; }
        public Nullable<byte> LateDeliveryReasonId { get; set; }
        public Nullable<System.DateTime> StockUpdateDate { get; set; }
        public byte StockTypeId { get; set; }
        public bool IsSepd { get; set; }
        public string Remarks { get; set; }
        public byte FlowTypeId { get; set; }
        public byte DeliveryProcessId { get; set; }
        public bool TripsheetStatus { get; set; }
        public bool ThcStatus { get; set; }
        public byte StatusId { get; set; }
        public bool IsTransit { get; set; }
        public bool IsDaccUpdated { get; set; }
    
        public virtual CL_Docket_History CL_Docket_History { get; set; }
    }
}
