//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Drs__MultiAdvance
    {
        public long DrsId { get; set; }
        public short AdvBalLoc { get; set; }
        public decimal AdvBalAmount { get; set; }
        public Nullable<bool> IsAdvanceDone { get; set; }
        public Nullable<long> VoucherId { get; set; }
    }
}
