//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Docket_Package
    {
        public long DocketId { get; set; }
        public long InvoiceId { get; set; }
        public string PackageNo { get; set; }
        public Nullable<bool> IsScan { get; set; }
    }
}
