//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Document_Nomenclature
    {
        public byte CompanyId { get; set; }
        public short WarehouseId { get; set; }
        public byte DocumentTypeId { get; set; }
        public string CompanyPrefix { get; set; }
        public string Separator { get; set; }
        public string Prefix1 { get; set; }
        public string Prefix2 { get; set; }
        public string Prefix3 { get; set; }
        public string Prefix4 { get; set; }
        public bool UseYear { get; set; }
        public bool IsFinYear { get; set; }
        public byte NomenclatureType { get; set; }
        public byte RunningNoLength { get; set; }
    }
}
