//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Deps_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Deps_Detail()
        {
            this.CL_Deps_History = new HashSet<CL_Deps_History>();
        }
    
        public long DepsDocketId { get; set; }
        public long DepsId { get; set; }
        public long DocketId { get; set; }
        public string DocketSuffix { get; set; }
        public int Packages { get; set; }
        public byte ReasonId { get; set; }
        public string Remark { get; set; }
        public string DocumentName { get; set; }
        public byte DepsStatus { get; set; }
    
        public virtual CL_Docket_Summary CL_Docket_Summary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Deps_History> CL_Deps_History { get; set; }
    }
}
