//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Docket_Status_Trn
    {
        public long DocketstatusId { get; set; }
        public long DocketId { get; set; }
        public System.DateTime StatueDate { get; set; }
        public long Status { get; set; }
        public string Remarks { get; set; }
        public string PODFile { get; set; }
        public string Extension { get; set; }
        public System.DateTime EntryDate { get; set; }
        public short EntryBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsFailed { get; set; }
    }
}
