//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Docket_Talk
    {
        public short TalkId { get; set; }
        public Nullable<long> DocketId { get; set; }
        public string Remarks { get; set; }
        public string DocumentName { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    }
}
