//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Error
    {
        public int ErrorId { get; set; }
        public Nullable<System.DateTime> GeneratedDate { get; set; }
        public string ModuleName { get; set; }
        public string ExceptionType { get; set; }
        public string Exception { get; set; }
        public string ExceptionSource { get; set; }
        public string StackTrace { get; set; }
        public string InnerExceptionType { get; set; }
        public string InnerException { get; set; }
        public string InnerSource { get; set; }
        public string InnerStackTrace { get; set; }
        public Nullable<bool> IsSolved { get; set; }
        public string Remark { get; set; }
        public Nullable<short> UserId { get; set; }
    }
}
