//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_EWayBill_Detail
    {
        public long CID { get; set; }
        public string status { get; set; }
        public string code { get; set; }
        public string eway_bill_number { get; set; }
        public string eway_bill_date { get; set; }
        public string eway_bill_valid_date { get; set; }
        public string number_of_valid_days { get; set; }
        public string eway_bill_status { get; set; }
        public string userGstin { get; set; }
        public string document_type { get; set; }
        public string document_number { get; set; }
        public string document_date { get; set; }
        public string gstin_of_consignor { get; set; }
        public string legal_name_of_consignor { get; set; }
        public string address1_of_consignor { get; set; }
        public string address2_of_consignor { get; set; }
        public string place_of_consignor { get; set; }
        public string pincode_of_consignor { get; set; }
        public string state_of_consignor { get; set; }
        public string actual_from_state_name { get; set; }
        public string gstin_of_consignee { get; set; }
        public string legal_name_of_consignee { get; set; }
        public string address1_of_consignee { get; set; }
        public string address2_of_consignee { get; set; }
        public string place_of_consignee { get; set; }
        public string pincode_of_consignee { get; set; }
        public string state_of_supply { get; set; }
        public string actual_to_state_name { get; set; }
        public string vehicle_number { get; set; }
        public Nullable<decimal> total_invoice_value { get; set; }
        public Nullable<decimal> taxable_amount { get; set; }
        public Nullable<decimal> cgst_amount { get; set; }
        public Nullable<decimal> sgst_amount { get; set; }
        public Nullable<decimal> igst_amount { get; set; }
        public string transporter_id { get; set; }
        public string transporter_name { get; set; }
        public string transportation_distance { get; set; }
        public string transporter_document_number { get; set; }
        public string transporter_document_date { get; set; }
        public Nullable<bool> isUsed { get; set; }
        public string transportation_mode { get; set; }
    }
}
