//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Flight_Schedule_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Flight_Schedule_Header()
        {
            this.CL_Flight_Days = new HashSet<CL_Flight_Days>();
            this.CL_Flight_Schedule_Detail = new HashSet<CL_Flight_Schedule_Detail>();
        }
    
        public short FlightId { get; set; }
        public string FlightNo { get; set; }
        public byte AirlineId { get; set; }
        public bool IsNRoute { get; set; }
        public byte FromAirportId { get; set; }
        public byte ToAirportId { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Flight_Days> CL_Flight_Days { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Flight_Schedule_Detail> CL_Flight_Schedule_Detail { get; set; }
        public virtual CL_Master_Airport CL_Master_Airport { get; set; }
        public virtual CL_Master_Airport CL_Master_Airport1 { get; set; }
    }
}
