//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_FuelRequest
    {
        public long FuelRequestId { get; set; }
        public string FuelRequestNo { get; set; }
        public short LocationId { get; set; }
        public Nullable<long> TripsheetId { get; set; }
        public System.DateTime FuelRequestDate { get; set; }
        public Nullable<decimal> StandardFuelInLiters { get; set; }
        public Nullable<decimal> StandardAdvanceAmount { get; set; }
        public Nullable<decimal> FuelRequestInLiters { get; set; }
        public Nullable<decimal> FuelRequestAdvanceAmount { get; set; }
        public short EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public Nullable<short> ApproveReject { get; set; }
        public Nullable<short> ApproveRejectBy { get; set; }
        public Nullable<decimal> BeforeApprovedFuelRequestInLiters { get; set; }
        public Nullable<decimal> BeforeApprovedFuelRequestAdvanceAmount { get; set; }
    
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        public virtual CL_Master_User CL_Master_User { get; set; }
        public virtual CL_Tripsheet_Header CL_Tripsheet_Header { get; set; }
    }
}
