//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Gatepass_Header
    {
        public long GatepassId { get; set; }
        public string GatepassNo { get; set; }
        public System.DateTime GatepassDate { get; set; }
        public short LocationId { get; set; }
        public long MrId { get; set; }
        public bool IsUpdated { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<short> CancelBy { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string VehicleNo { get; set; }
        public string Remarks { get; set; }
    }
}
