//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Grn_Detail
    {
        public long GrnId { get; set; }
        public System.DateTime GrnDate { get; set; }
        public int ProductId { get; set; }
        public decimal DocumentQuantity { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> ShortExcess { get; set; }
        public decimal InspectionQuantity { get; set; }
        public decimal GoodQuantity { get; set; }
        public decimal DamageQuantity { get; set; }
        public decimal PutAwayQuantity { get; set; }
        public bool InspectionStatus { get; set; }
        public bool OnHold { get; set; }
        public int Packages { get; set; }
    }
}
