//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Inspection_Detail
    {
        public long InspectionId { get; set; }
        public long GrnId { get; set; }
        public int ProductId { get; set; }
        public decimal GrnQuantity { get; set; }
        public decimal ApproveQuantity { get; set; }
        public decimal RejectQuantity { get; set; }
        public byte RejectReason { get; set; }
        public decimal RepackingQuantity { get; set; }
        public string Remarks { get; set; }
        public decimal InspectionQuantity { get; set; }
        public bool RepackingStatus { get; set; }
    
        public virtual CL_Inspection_Header CL_Inspection_Header { get; set; }
    }
}
