//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_JobOrder_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_JobOrder_Header()
        {
            this.CL_JobOrder_SparePart_Detail = new HashSet<CL_JobOrder_SparePart_Detail>();
            this.CL_JobOrder_Task_Detail = new HashSet<CL_JobOrder_Task_Detail>();
            this.CL_SpareRequest_Header = new HashSet<CL_SpareRequest_Header>();
        }
    
        public long JobOrderId { get; set; }
        public string JobOrderNo { get; set; }
        public short LocationId { get; set; }
        public short VehicleId { get; set; }
        public string VehicleNo { get; set; }
        public System.DateTime JobOrderDate { get; set; }
        public byte JobCardType { get; set; }
        public byte ServiceCenterType { get; set; }
        public byte ServiceCenterId { get; set; }
        public System.DateTime SendDate { get; set; }
        public System.DateTime EstimatedReturnDate { get; set; }
        public int CurrentKmReading { get; set; }
        public int CloseKmReading { get; set; }
        public Nullable<System.DateTime> ActualReturnDate { get; set; }
        public decimal LabourCostPerHour { get; set; }
        public byte TotalEstimatedLabourHours { get; set; }
        public decimal TotalEstimatedLabourCost { get; set; }
        public decimal TotalEstimatedCost { get; set; }
        public decimal TotalActualLabourCost { get; set; }
        public decimal TotalEstimatedSparePartCost { get; set; }
        public decimal TotalActualSparePartCost { get; set; }
        public bool IsClose { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<short> CloseBy { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public decimal TotalActualCost { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public string RejectReason { get; set; }
        public byte CompanyId { get; set; }
    
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        public virtual CL_Master_Vehicle CL_Master_Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_JobOrder_SparePart_Detail> CL_JobOrder_SparePart_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_JobOrder_Task_Detail> CL_JobOrder_Task_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_SpareRequest_Header> CL_SpareRequest_Header { get; set; }
    }
}
