//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_JobOrder_SparePart_Detail
    {
        public long JobOrderId { get; set; }
        public byte SkuId { get; set; }
        public byte TaskTypeId { get; set; }
        public int RequestedQuantity { get; set; }
        public decimal CostPerUnit { get; set; }
        public decimal Cost { get; set; }
        public string Remarks { get; set; }
        public int ActualQuantity { get; set; }
        public decimal ActualCostPerUnit { get; set; }
        public decimal ActualCost { get; set; }
    
        public virtual CL_JobOrder_Header CL_JobOrder_Header { get; set; }
        public virtual CL_Master_SKU CL_Master_SKU { get; set; }
    }
}
