//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_LoadingSheet_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_LoadingSheet_Header()
        {
            this.CL_LoadingSheet_Detail = new HashSet<CL_LoadingSheet_Detail>();
        }
    
        public long LoadingSheetId { get; set; }
        public string LoadingSheetNo { get; set; }
        public System.DateTime LoadingSheetDate { get; set; }
        public System.TimeSpan LoadingSheetTime { get; set; }
        public Nullable<System.DateTime> LoadingSheetDateTime { get; set; }
        public string ManualLoadingSheetNo { get; set; }
        public short LocationId { get; set; }
        public short NextLocationId { get; set; }
        public short TotalDocket { get; set; }
        public int TotalPackages { get; set; }
        public decimal TotalActualWeight { get; set; }
        public bool ManifestStatus { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public byte CompanyId { get; set; }
        public Nullable<short> CancelBy { get; set; }
        public Nullable<long> ManifestId { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_LoadingSheet_Detail> CL_LoadingSheet_Detail { get; set; }
        public virtual CL_Master_Location CL_Master_Location { get; set; }
    }
}
