//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_JobOrder_Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_JobOrder_Task()
        {
            this.CL_JobOrder_Task_Detail = new HashSet<CL_JobOrder_Task_Detail>();
        }
    
        public byte WorkGroupId { get; set; }
        public byte TaskTypeId { get; set; }
        public short TaskId { get; set; }
        public string Task { get; set; }
        public byte EstimatedLabourHours { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_JobOrder_Task_Detail> CL_JobOrder_Task_Detail { get; set; }
        public virtual CL_Master_JobOrder_TaskType CL_Master_JobOrder_TaskType { get; set; }
        public virtual CL_Master_JobOrder_WorkGroup CL_Master_JobOrder_WorkGroup { get; set; }
    }
}
