//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_VendorContract_RouteBased
    {
        public short ContractId { get; set; }
        public short RouteId { get; set; }
        public byte FtlTypeId { get; set; }
        public short VehicleId { get; set; }
        public decimal MinimumCharge { get; set; }
        public decimal MaximumCharge { get; set; }
        public byte RateTypeId { get; set; }
        public decimal Rate { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<byte> TransportModeId { get; set; }
    
        public virtual CL_Master_Route CL_Master_Route { get; set; }
        public virtual CL_Master_VendorContract CL_Master_VendorContract { get; set; }
    }
}
