//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_SKU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_SKU()
        {
            this.CL_JobOrder_SparePart_Detail = new HashSet<CL_JobOrder_SparePart_Detail>();
            this.CL_PO_Grn_Detail = new HashSet<CL_PO_Grn_Detail>();
            this.CL_PurchaseOrder_Detail = new HashSet<CL_PurchaseOrder_Detail>();
            this.CL_SpareRequest_Detail = new HashSet<CL_SpareRequest_Detail>();
        }
    
        public byte SkuId { get; set; }
        public byte MaterialCategoryId { get; set; }
        public string SkuName { get; set; }
        public string Manufacture { get; set; }
        public byte SkuType { get; set; }
        public byte SkuSize { get; set; }
        public byte UomId { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string SkuCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_JobOrder_SparePart_Detail> CL_JobOrder_SparePart_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_PO_Grn_Detail> CL_PO_Grn_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_PurchaseOrder_Detail> CL_PurchaseOrder_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_SpareRequest_Detail> CL_SpareRequest_Detail { get; set; }
    }
}
