//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_ManifestLabourDC_Header
    {
        public long LabourDCId { get; set; }
        public string LabourDCNo { get; set; }
        public System.DateTime LabourDCDate { get; set; }
        public string ManualLabourDCNo { get; set; }
        public Nullable<short> VendorId { get; set; }
        public short LocationId { get; set; }
        public short TotalManifest { get; set; }
        public int TotalPackages { get; set; }
        public decimal TotalActualWeight { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public Nullable<short> CancelBy { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public byte CompanyId { get; set; }
        public Nullable<bool> isBilled { get; set; }
        public string DocumentType { get; set; }
        public string THCType { get; set; }
        public Nullable<short> BillLocationId { get; set; }
    }
}
