//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_VendorContract_DocketBased
    {
        public short ContractId { get; set; }
        public short FromLocationId { get; set; }
        public short ToLocationId { get; set; }
        public byte PaybasId { get; set; }
        public byte TransportModeId { get; set; }
        public bool IsBooking { get; set; }
        public decimal MinimumCharge { get; set; }
        public decimal MaximumCharge { get; set; }
        public byte RateTypeId { get; set; }
        public decimal Rate { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool IsBaDoorPickup { get; set; }
        public bool IsBaDoorDelivery { get; set; }
        public byte ProductTypeId { get; set; }
        public byte PackagingTypeId { get; set; }
        public string ServiceType { get; set; }
        public Nullable<decimal> LabourRate { get; set; }
        public string LabourRateType { get; set; }
        public string WeightType { get; set; }
    
        public virtual CL_Master_VendorContract CL_Master_VendorContract { get; set; }
    }
}
