//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Manifest_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Manifest_Header()
        {
            this.CL_Manifest_Detail = new HashSet<CL_Manifest_Detail>();
            this.CL_Thc_Manifest_Detail = new HashSet<CL_Thc_Manifest_Detail>();
        }
    
        public long ManifestId { get; set; }
        public string ManifestNo { get; set; }
        public System.DateTime ManifestDate { get; set; }
        public System.TimeSpan ManifestTime { get; set; }
        public Nullable<System.DateTime> ManifestDateTime { get; set; }
        public string ManualManifestNo { get; set; }
        public short LocationId { get; set; }
        public short NextLocationId { get; set; }
        public short TotalDocket { get; set; }
        public int TotalPackages { get; set; }
        public decimal TotalActualWeight { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public byte CompanyId { get; set; }
        public bool IsThc { get; set; }
        public Nullable<short> CancelBy { get; set; }
        public Nullable<long> LoadingSheetId { get; set; }
        public Nullable<long> ThcId { get; set; }
        public Nullable<bool> isLabourDC { get; set; }
        public Nullable<bool> isLabourBilling { get; set; }
        public Nullable<decimal> TotalLabourAmount { get; set; }
        public Nullable<short> VendorId { get; set; }
        public Nullable<decimal> TotalDeliveryKartAmount { get; set; }
        public Nullable<decimal> TotalDeliveryLabourAmount { get; set; }
        public Nullable<bool> isUseinBilling { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Manifest_Detail> CL_Manifest_Detail { get; set; }
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Thc_Manifest_Detail> CL_Thc_Manifest_Detail { get; set; }
    }
}
