//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_CustomerContract_BasicInfo
    {
        public short ContractId { get; set; }
        public string ManualContractId { get; set; }
        public System.DateTime ContractDate { get; set; }
        public short LocationId { get; set; }
        public string DocumentName { get; set; }
        public byte PartyCategory { get; set; }
        public byte ContractCategory { get; set; }
        public string AccountPersonName { get; set; }
        public string AccountPersonMobileNo { get; set; }
        public string AccountPersonEmailId { get; set; }
        public string CseName { get; set; }
        public string CseMobileNo { get; set; }
        public string CseEmailId { get; set; }
        public string AccountRepresentativeName { get; set; }
        public string Remarks { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual CL_Master_CustomerContract CL_Master_CustomerContract { get; set; }
        public virtual CL_Master_Location CL_Master_Location { get; set; }
    }
}
