//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_Vehicle()
        {
            this.CL_Drs_Header = new HashSet<CL_Drs_Header>();
            this.CL_JobOrder_Header = new HashSet<CL_JobOrder_Header>();
            this.CL_Master_Driver = new HashSet<CL_Master_Driver>();
            this.CL_Master_Fuel_Card = new HashSet<CL_Master_Fuel_Card>();
            this.CL_Prs_Header = new HashSet<CL_Prs_Header>();
            this.CL_Tripsheet_Header = new HashSet<CL_Tripsheet_Header>();
        }
    
        public short VehicleId { get; set; }
        public string VehicleNo { get; set; }
        public short VehicleTypeId { get; set; }
        public short VendorId { get; set; }
        public byte FtlTypeId { get; set; }
        public bool IsActive { get; set; }
        public short LocationId { get; set; }
        public Nullable<int> StartKm { get; set; }
        public bool VehicleStatus { get; set; }
        public Nullable<bool> IsAttach { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Drs_Header> CL_Drs_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_JobOrder_Header> CL_JobOrder_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Driver> CL_Master_Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Fuel_Card> CL_Master_Fuel_Card { get; set; }
        public virtual CL_Master_Vehicle_Detail CL_Master_Vehicle_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Prs_Header> CL_Prs_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Tripsheet_Header> CL_Tripsheet_Header { get; set; }
    }
}
