//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Asset
    {
        public short AssetId { get; set; }
        public string AssetCode { get; set; }
        public string AssetName { get; set; }
        public string AssetPrefix { get; set; }
        public short AssetGroupId { get; set; }
        public byte UomId { get; set; }
        public Nullable<byte> AssetCategory { get; set; }
        public Nullable<byte> DepreciationMethod { get; set; }
        public decimal DepreciationRate { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual CL_Master_AccountGroup CL_Master_AccountGroup { get; set; }
    }
}
