//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_VendorContract_LoadingUnloading
    {
        public short ContractId { get; set; }
        public Nullable<byte> LoadingRateTypeId { get; set; }
        public decimal LoadingRate { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<byte> UnloadingRateTypeId { get; set; }
        public decimal UnloadingRate { get; set; }
    
        public virtual CL_Master_VendorContract CL_Master_VendorContract { get; set; }
    }
}
