//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Tax_Setting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_Tax_Setting()
        {
            this.CL_Master_Tax = new HashSet<CL_Master_Tax>();
        }
    
        public byte TaxCode { get; set; }
        public byte BaseOn { get; set; }
        public string TaxName { get; set; }
        public short AccountId { get; set; }
        public string Narration { get; set; }
        public Nullable<short> OppositeAccountId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Tax> CL_Master_Tax { get; set; }
    }
}
