//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_Account()
        {
            this.CL_Cheque_Detail = new HashSet<CL_Cheque_Detail>();
            this.CL_CustomerBill_Supplementry_Detail = new HashSet<CL_CustomerBill_Supplementry_Detail>();
            this.CL_VendorBill_OtherDetail = new HashSet<CL_VendorBill_OtherDetail>();
            this.CL_Account_Transaction = new HashSet<CL_Account_Transaction>();
            this.CL_Account_Transaction1 = new HashSet<CL_Account_Transaction>();
            this.CL_Master_AccountOpening = new HashSet<CL_Master_AccountOpening>();
            this.CL_Master_AccountOpening_Party = new HashSet<CL_Master_AccountOpening_Party>();
            this.CL_Master_Budget = new HashSet<CL_Master_Budget>();
            this.CL_Master_Card = new HashSet<CL_Master_Card>();
            this.CL_Master_Charge = new HashSet<CL_Master_Charge>();
            this.CL_Master_Fuel_Card = new HashSet<CL_Master_Fuel_Card>();
            this.CL_Master_JobOrder_TaskType = new HashSet<CL_Master_JobOrder_TaskType>();
            this.CL_Voucher_AccountDetail = new HashSet<CL_Voucher_AccountDetail>();
            this.CL_Master_Location = new HashSet<CL_Master_Location>();
        }
    
        public short AccountId { get; set; }
        public string AccountCode { get; set; }
        public byte AccountCategoryId { get; set; }
        public short AccountGroupId { get; set; }
        public string AccountDescription { get; set; }
        public byte CompanyId { get; set; }
        public byte PartyTypeId { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> MappedAccountId { get; set; }
        public string PartyCode { get; set; }
        public Nullable<byte> MainAccountCategoryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Cheque_Detail> CL_Cheque_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CustomerBill_Supplementry_Detail> CL_CustomerBill_Supplementry_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_VendorBill_OtherDetail> CL_VendorBill_OtherDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Account_Transaction> CL_Account_Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Account_Transaction> CL_Account_Transaction1 { get; set; }
        public virtual CL_Master_AccountCategory CL_Master_AccountCategory { get; set; }
        public virtual CL_Master_AccountGroup CL_Master_AccountGroup { get; set; }
        public virtual CL_Master_Company CL_Master_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_AccountOpening> CL_Master_AccountOpening { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_AccountOpening_Party> CL_Master_AccountOpening_Party { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Budget> CL_Master_Budget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Card> CL_Master_Card { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Charge> CL_Master_Charge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Fuel_Card> CL_Master_Fuel_Card { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_JobOrder_TaskType> CL_Master_JobOrder_TaskType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Voucher_AccountDetail> CL_Voucher_AccountDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Location> CL_Master_Location { get; set; }
    }
}
