//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_CustomerContract_Services
    {
        public short ContractId { get; set; }
        public bool UseVolumetric { get; set; }
        public string VolumetricWeightType { get; set; }
        public bool UseInvoiceNo { get; set; }
        public bool UseInvoiceDate { get; set; }
        public bool UseDeferement { get; set; }
        public byte DefermentDays { get; set; }
        public bool UseFreightAsInvoicePercentage { get; set; }
        public decimal FreightInvoicePercentage { get; set; }
        public bool UseFreightDiscount { get; set; }
        public decimal FreightDiscountPercentage { get; set; }
        public Nullable<short> FreightContractId { get; set; }
        public bool UseDeliveryReattempt { get; set; }
        public byte DeliveryReattemptCount { get; set; }
        public bool UseMinimumFreightTypeBaseWise { get; set; }
        public bool UseFreightRateLimit { get; set; }
        public bool UseSubTotalLimit { get; set; }
        public bool UseCod { get; set; }
        public decimal CodRate { get; set; }
        public byte CodRateType { get; set; }
        public decimal MinimumCodAmount { get; set; }
        public decimal MaximumCodAmount { get; set; }
        public bool UseDacc { get; set; }
        public decimal DaccRate { get; set; }
        public byte DaccRateType { get; set; }
        public decimal MinimumDaccAmount { get; set; }
        public decimal MaximumDaccAmount { get; set; }
        public bool UseOctroi { get; set; }
        public decimal OctroiRate { get; set; }
        public byte OctroiRateType { get; set; }
        public decimal MinimumOctroiAmount { get; set; }
        public decimal MaximumOctroiAmount { get; set; }
        public bool UseOda { get; set; }
        public bool UseFuelSurcharge { get; set; }
        public bool UseDeliveryWithoutDemurrage { get; set; }
        public decimal DemurrageRate { get; set; }
        public byte DemurrageRateType { get; set; }
        public decimal MinimumDemurrageAmount { get; set; }
        public decimal MaximumDemurrageAmount { get; set; }
        public byte DemurrageFreeStorageDays { get; set; }
        public bool UseDemurrageBasInclusiveStorageDays { get; set; }
        public bool IsGstApplicable { get; set; }
        public bool UseMultipointChargesForChild { get; set; }
        public bool IsCarrierRisk { get; set; }
        public byte OdaSlabType { get; set; }
        public byte OdaRateType { get; set; }
        public decimal MinimumOdaCharge { get; set; }
        public decimal MaximumOdaCharge { get; set; }
        public bool UseLatePenaltyCharge { get; set; }
        public bool UsePartVolumetric { get; set; }
    
        public virtual CL_Master_CustomerContract CL_Master_CustomerContract { get; set; }
        public virtual CL_Master_CustomerContract CL_Master_CustomerContract1 { get; set; }
    }
}
