//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Rules
    {
        public byte ModuleId { get; set; }
        public short RuleId { get; set; }
        public byte PaybasId { get; set; }
        public string RuleDescription { get; set; }
        public string RuleValue { get; set; }
        public Nullable<int> RuleType { get; set; }
    }
}
