//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_Location()
        {
            this.CL_Adjustment_Header = new HashSet<CL_Adjustment_Header>();
            this.CL_Advice = new HashSet<CL_Advice>();
            this.CL_Advice1 = new HashSet<CL_Advice>();
            this.CL_CustomerBill_Header = new HashSet<CL_CustomerBill_Header>();
            this.CL_CustomerBill_Header1 = new HashSet<CL_CustomerBill_Header>();
            this.CL_CustomerBill_Header2 = new HashSet<CL_CustomerBill_Header>();
            this.CL_DCR = new HashSet<CL_DCR>();
            this.CL_Deps_History = new HashSet<CL_Deps_History>();
            this.CL_Docket = new HashSet<CL_Docket>();
            this.CL_Docket1 = new HashSet<CL_Docket>();
            this.CL_Docket2 = new HashSet<CL_Docket>();
            this.CL_Docket_Status = new HashSet<CL_Docket_Status>();
            this.CL_Docket_Summary = new HashSet<CL_Docket_Summary>();
            this.CL_Drs_Header = new HashSet<CL_Drs_Header>();
            this.CL_JobOrder_Header = new HashSet<CL_JobOrder_Header>();
            this.CL_LoadingSheet_Header = new HashSet<CL_LoadingSheet_Header>();
            this.CL_Manifest_Header = new HashSet<CL_Manifest_Header>();
            this.CL_Master_AccountOpening = new HashSet<CL_Master_AccountOpening>();
            this.CL_Master_AccountOpening_Party = new HashSet<CL_Master_AccountOpening_Party>();
            this.CL_Master_Budget = new HashSet<CL_Master_Budget>();
            this.CL_Master_CustomerContract_BasicInfo = new HashSet<CL_Master_CustomerContract_BasicInfo>();
            this.CL_Master_CustomerContract_BillingInfo = new HashSet<CL_Master_CustomerContract_BillingInfo>();
            this.CL_Master_CustomerContract_BillingInfo1 = new HashSet<CL_Master_CustomerContract_BillingInfo>();
            this.CL_Master_CustomerContract_BillingInfo2 = new HashSet<CL_Master_CustomerContract_BillingInfo>();
            this.CL_Master_Driver = new HashSet<CL_Master_Driver>();
            this.CL_FuelRequest = new HashSet<CL_FuelRequest>();
            this.CL_Master_CustomerContract_ChargeMatrix_FCL = new HashSet<CL_Master_CustomerContract_ChargeMatrix_FCL>();
            this.CL_Master_CustomerContract_ChargeMatrix_FTL = new HashSet<CL_Master_CustomerContract_ChargeMatrix_FTL>();
            this.CL_Master_CustomerContract_ChargeMatrix_LTL = new HashSet<CL_Master_CustomerContract_ChargeMatrix_LTL>();
            this.CL_Master_Location1 = new HashSet<CL_Master_Location>();
            this.CL_Master_Pincode = new HashSet<CL_Master_Pincode>();
            this.CL_Master_Receiver = new HashSet<CL_Master_Receiver>();
            this.CL_Master_Route_Detail = new HashSet<CL_Master_Route_Detail>();
            this.CL_Master_Route = new HashSet<CL_Master_Route>();
            this.CL_Master_User = new HashSet<CL_Master_User>();
            this.CL_Master_VendorContract_BasicInfo = new HashSet<CL_Master_VendorContract_BasicInfo>();
            this.CL_Master_VendorContract_BasicInfo1 = new HashSet<CL_Master_VendorContract_BasicInfo>();
            this.CL_Master_VendorContract_CrossingBased = new HashSet<CL_Master_VendorContract_CrossingBased>();
            this.CL_Master_Warehouse = new HashSet<CL_Master_Warehouse>();
            this.CL_Mr_Header = new HashSet<CL_Mr_Header>();
            this.CL_PO_Grn_Header = new HashSet<CL_PO_Grn_Header>();
            this.CL_Pod = new HashSet<CL_Pod>();
            this.CL_Prs_Header = new HashSet<CL_Prs_Header>();
            this.CL_PurchaseOrder_Header = new HashSet<CL_PurchaseOrder_Header>();
            this.CL_SpareRequest_Header = new HashSet<CL_SpareRequest_Header>();
            this.CL_Thc_Header = new HashSet<CL_Thc_Header>();
            this.CL_Thc_Header1 = new HashSet<CL_Thc_Header>();
            this.CL_Thc_Header2 = new HashSet<CL_Thc_Header>();
            this.CL_Thc_Header3 = new HashSet<CL_Thc_Header>();
            this.CL_Tripsheet_ExpectedDriverAdvance = new HashSet<CL_Tripsheet_ExpectedDriverAdvance>();
            this.CL_Tripsheet_Header = new HashSet<CL_Tripsheet_Header>();
            this.CL_Tripsheet_Advance = new HashSet<CL_Tripsheet_Advance>();
            this.CL_Tripsheet_Header1 = new HashSet<CL_Tripsheet_Header>();
            this.CL_Unloading_Header = new HashSet<CL_Unloading_Header>();
            this.CL_VendorBill_Header = new HashSet<CL_VendorBill_Header>();
            this.CL_VendorPayment_Header = new HashSet<CL_VendorPayment_Header>();
            this.CL_Voucher_Detail = new HashSet<CL_Voucher_Detail>();
            this.CL_Voucher_Summary = new HashSet<CL_Voucher_Summary>();
            this.CL_Master_Account = new HashSet<CL_Master_Account>();
            this.CL_Master_Customer = new HashSet<CL_Master_Customer>();
            this.CL_Master_Holiday_Datewise = new HashSet<CL_Master_Holiday_Datewise>();
            this.CL_Master_Location11 = new HashSet<CL_Master_Location>();
            this.CL_Master_Location3 = new HashSet<CL_Master_Location>();
            this.CL_Master_Vendor = new HashSet<CL_Master_Vendor>();
        }
    
        public short LocationId { get; set; }
        public Nullable<byte> CountryId { get; set; }
        public byte LocationHierarchyId { get; set; }
        public string LocationCode { get; set; }
        public string LocationName { get; set; }
        public Nullable<short> ReportLocationId { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsComputerized { get; set; }
        public byte OwnershipTypeId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Pincode { get; set; }
        public string ReportLocationCode { get; set; }
        public string ReportLocationName { get; set; }
        public bool IsCutOffApplicable { get; set; }
        public Nullable<System.TimeSpan> CutOffStartTime { get; set; }
        public Nullable<System.TimeSpan> CutOffEndTime { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> ownershipLocationId { get; set; }
        public string InternalLocationCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Adjustment_Header> CL_Adjustment_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Advice> CL_Advice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Advice> CL_Advice1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CustomerBill_Header> CL_CustomerBill_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CustomerBill_Header> CL_CustomerBill_Header1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CustomerBill_Header> CL_CustomerBill_Header2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_DCR> CL_DCR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Deps_History> CL_Deps_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Docket> CL_Docket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Docket> CL_Docket1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Docket> CL_Docket2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Docket_Status> CL_Docket_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Docket_Summary> CL_Docket_Summary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Drs_Header> CL_Drs_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_JobOrder_Header> CL_JobOrder_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_LoadingSheet_Header> CL_LoadingSheet_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Manifest_Header> CL_Manifest_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_AccountOpening> CL_Master_AccountOpening { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_AccountOpening_Party> CL_Master_AccountOpening_Party { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Budget> CL_Master_Budget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_CustomerContract_BasicInfo> CL_Master_CustomerContract_BasicInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_CustomerContract_BillingInfo> CL_Master_CustomerContract_BillingInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_CustomerContract_BillingInfo> CL_Master_CustomerContract_BillingInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_CustomerContract_BillingInfo> CL_Master_CustomerContract_BillingInfo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Driver> CL_Master_Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_FuelRequest> CL_FuelRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_CustomerContract_ChargeMatrix_FCL> CL_Master_CustomerContract_ChargeMatrix_FCL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_CustomerContract_ChargeMatrix_FTL> CL_Master_CustomerContract_ChargeMatrix_FTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_CustomerContract_ChargeMatrix_LTL> CL_Master_CustomerContract_ChargeMatrix_LTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Location> CL_Master_Location1 { get; set; }
        public virtual CL_Master_Location CL_Master_Location2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Pincode> CL_Master_Pincode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Receiver> CL_Master_Receiver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Route_Detail> CL_Master_Route_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Route> CL_Master_Route { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_User> CL_Master_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_VendorContract_BasicInfo> CL_Master_VendorContract_BasicInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_VendorContract_BasicInfo> CL_Master_VendorContract_BasicInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_VendorContract_CrossingBased> CL_Master_VendorContract_CrossingBased { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Warehouse> CL_Master_Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Mr_Header> CL_Mr_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_PO_Grn_Header> CL_PO_Grn_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Pod> CL_Pod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Prs_Header> CL_Prs_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_PurchaseOrder_Header> CL_PurchaseOrder_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_SpareRequest_Header> CL_SpareRequest_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Thc_Header> CL_Thc_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Thc_Header> CL_Thc_Header1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Thc_Header> CL_Thc_Header2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Thc_Header> CL_Thc_Header3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Tripsheet_ExpectedDriverAdvance> CL_Tripsheet_ExpectedDriverAdvance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Tripsheet_Header> CL_Tripsheet_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Tripsheet_Advance> CL_Tripsheet_Advance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Tripsheet_Header> CL_Tripsheet_Header1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Unloading_Header> CL_Unloading_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_VendorBill_Header> CL_VendorBill_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_VendorPayment_Header> CL_VendorPayment_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Voucher_Detail> CL_Voucher_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Voucher_Summary> CL_Voucher_Summary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Account> CL_Master_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Customer> CL_Master_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Holiday_Datewise> CL_Master_Holiday_Datewise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Location> CL_Master_Location11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Location> CL_Master_Location3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Vendor> CL_Master_Vendor { get; set; }
    }
}
