//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_FSCRate
    {
        public long FSCRateId { get; set; }
        public byte CompanyId { get; set; }
        public short CustomerId { get; set; }
        public long LaneId { get; set; }
        public System.DateTime PeriodFrom { get; set; }
        public System.DateTime PeriodTo { get; set; }
        public Nullable<byte> ContractID { get; set; }
        public Nullable<decimal> VariableBaseAmtPerTrip { get; set; }
        public Nullable<decimal> FuelBasePrice { get; set; }
        public Nullable<decimal> NewFuelPrice { get; set; }
        public Nullable<decimal> TotalTripFSCAmount { get; set; }
        public bool IsActive { get; set; }
        public string EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual CL_Master_Company CL_Master_Company { get; set; }
        public virtual CL_Master_Customer CL_Master_Customer { get; set; }
    }
}
