//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_Company()
        {
            this.CL_Adjustment_Header = new HashSet<CL_Adjustment_Header>();
            this.CL_Advice = new HashSet<CL_Advice>();
            this.CL_Cheque_Detail = new HashSet<CL_Cheque_Detail>();
            this.CL_CustomerBill_Header = new HashSet<CL_CustomerBill_Header>();
            this.CL_Master_Account = new HashSet<CL_Master_Account>();
            this.CL_Master_AccountOpening = new HashSet<CL_Master_AccountOpening>();
            this.CL_Master_Budget = new HashSet<CL_Master_Budget>();
            this.CL_Master_FSCRate = new HashSet<CL_Master_FSCRate>();
            this.CL_Master_Lane = new HashSet<CL_Master_Lane>();
            this.CL_Master_User_Company_Mapping = new HashSet<CL_Master_User_Company_Mapping>();
            this.CL_Mr_Header = new HashSet<CL_Mr_Header>();
            this.CL_Unloading_Header = new HashSet<CL_Unloading_Header>();
        }
    
        public byte CompanyId { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string ContactPerson { get; set; }
        public string MobileNo { get; set; }
        public string GstTinNo { get; set; }
        public string PANNo { get; set; }
        public string TANNo { get; set; }
        public string RegistrationNo { get; set; }
        public string PunchLine { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public byte[] CompanyLogo { get; set; }
        public string EmailId { get; set; }
        public string Website { get; set; }
        public System.DateTime StartDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Adjustment_Header> CL_Adjustment_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Advice> CL_Advice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Cheque_Detail> CL_Cheque_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CustomerBill_Header> CL_CustomerBill_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Account> CL_Master_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_AccountOpening> CL_Master_AccountOpening { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Budget> CL_Master_Budget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_FSCRate> CL_Master_FSCRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Lane> CL_Master_Lane { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_User_Company_Mapping> CL_Master_User_Company_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Mr_Header> CL_Mr_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Unloading_Header> CL_Unloading_Header { get; set; }
    }
}
