//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_Customer()
        {
            this.CL_CustomerBill_Header = new HashSet<CL_CustomerBill_Header>();
            this.CL_Master_Customer_Address_Mapping = new HashSet<CL_Master_Customer_Address_Mapping>();
            this.CL_Master_Customer_Paybas_Mapping = new HashSet<CL_Master_Customer_Paybas_Mapping>();
            this.CL_Master_CustomerBillFormat = new HashSet<CL_Master_CustomerBillFormat>();
            this.CL_Master_FSCRate = new HashSet<CL_Master_FSCRate>();
            this.CL_Master_Lane = new HashSet<CL_Master_Lane>();
            this.CL_Master_Product_Customer_Mapping = new HashSet<CL_Master_Product_Customer_Mapping>();
            this.CL_Master_Product_Customer_Mapping1 = new HashSet<CL_Master_Product_Customer_Mapping>();
            this.CL_Mr_Header = new HashSet<CL_Mr_Header>();
            this.CL_Tripsheet_Header = new HashSet<CL_Tripsheet_Header>();
            this.CL_Master_Location = new HashSet<CL_Master_Location>();
        }
    
        public string GroupCode { get; set; }
        public short CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public bool IsActive { get; set; }
        public byte CompanyId { get; set; }
        public string EmailId1 { get; set; }
        public string EmailId2 { get; set; }
        public string EmailId3 { get; set; }
        public string EmailId4 { get; set; }
        public Nullable<bool> IsSez { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CustomerBill_Header> CL_CustomerBill_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Customer_Address_Mapping> CL_Master_Customer_Address_Mapping { get; set; }
        public virtual CL_Master_Customer_AddressInfo CL_Master_Customer_AddressInfo { get; set; }
        public virtual CL_Master_Customer_Detail CL_Master_Customer_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Customer_Paybas_Mapping> CL_Master_Customer_Paybas_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_CustomerBillFormat> CL_Master_CustomerBillFormat { get; set; }
        public virtual CL_Master_CustomerGroup CL_Master_CustomerGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_FSCRate> CL_Master_FSCRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Lane> CL_Master_Lane { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Product_Customer_Mapping> CL_Master_Product_Customer_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Product_Customer_Mapping> CL_Master_Product_Customer_Mapping1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Mr_Header> CL_Mr_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Tripsheet_Header> CL_Tripsheet_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Location> CL_Master_Location { get; set; }
    }
}
