//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Gst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_Gst()
        {
            this.CL_Docket_Charge = new HashSet<CL_Docket_Charge>();
            this.CL_Voucher_Summary = new HashSet<CL_Voucher_Summary>();
        }
    
        public long GstId { get; set; }
        public string GstTinNo { get; set; }
        public byte OwnerType { get; set; }
        public long OwnerId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Address { get; set; }
        public string ProvisionalId { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public short StateId { get; set; }
        public string RegistrationType { get; set; }
        public string Pincode { get; set; }
        public string PanNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Docket_Charge> CL_Docket_Charge { get; set; }
        public virtual CL_Master_State CL_Master_State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Voucher_Summary> CL_Voucher_Summary { get; set; }
    }
}
