//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Rate
    {
        public short ExpenseId { get; set; }
        public Nullable<byte> PayBasId { get; set; }
        public byte TransportModeId { get; set; }
        public byte MatrixTypeId { get; set; }
        public short FromLocationId { get; set; }
        public short ToLocationId { get; set; }
        public byte RateTypeId { get; set; }
        public decimal Rate { get; set; }
        public byte CompanyId { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> CancelBy { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
    }
}
