//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_CustomerContract_ModewiseServices
    {
        public short ContractId { get; set; }
        public byte TransportModeId { get; set; }
        public decimal CftRatio { get; set; }
        public string CftMeasurementType { get; set; }
        public Nullable<System.TimeSpan> CutOffStartTime { get; set; }
        public Nullable<System.TimeSpan> CutOffEndTime { get; set; }
        public byte CutOffTransitDays { get; set; }
        public Nullable<decimal> FuelSurchargeRate { get; set; }
        public byte FuelSurchargeRateType { get; set; }
        public decimal MinimumFuelSurchargeAmount { get; set; }
        public decimal MaximumFuelSurchargeAmount { get; set; }
        public Nullable<decimal> MinimumFreightRate { get; set; }
        public string MinimumFreightRateType { get; set; }
        public decimal MinimumFreightAmount { get; set; }
        public Nullable<decimal> MinimumFreightLowerLimit { get; set; }
        public Nullable<decimal> MinimumFreightUpperLimit { get; set; }
        public decimal MinimumSubTotalAmount { get; set; }
        public Nullable<decimal> SubTotalLowerLimit { get; set; }
        public Nullable<decimal> SubTotalUpperLimit { get; set; }
        public byte DefaultServiceTaxPayer { get; set; }
        public bool IsServiceTaxPayerEnabled { get; set; }
        public Nullable<decimal> LatePenaltyChargeRate { get; set; }
        public Nullable<byte> LatePenaltyChargeRateType { get; set; }
        public Nullable<decimal> MinimumLatePenaltyChargeAmount { get; set; }
        public Nullable<decimal> MaximumLatePenaltyChargeAmount { get; set; }
        public byte FreeExclusiveDays { get; set; }
        public Nullable<decimal> MinimumChargedWeightRate { get; set; }
        public string MinimumChargedWeightRateType { get; set; }
        public Nullable<decimal> DividerCftMeasurement { get; set; }
        public string DividerCftMeasurementType { get; set; }
    
        public virtual CL_Master_CustomerContract CL_Master_CustomerContract { get; set; }
    }
}
