//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Charge
    {
        public byte ChargeType { get; set; }
        public byte ChargeCode { get; set; }
        public string ChargeName { get; set; }
        public byte BaseOn { get; set; }
        public byte BaseCode { get; set; }
        public bool IsOperator { get; set; }
        public bool IsActive { get; set; }
        public bool UseBookTime { get; set; }
        public bool UseDeliveryTime { get; set; }
        public Nullable<short> AccountId { get; set; }
        public Nullable<bool> IsGstApplicable { get; set; }
    
        public virtual CL_Master_Account CL_Master_Account { get; set; }
    }
}
