//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_State_Document
    {
        public short StateId { get; set; }
        public string DocumentName { get; set; }
        public bool IsInbound { get; set; }
        public short StateDocumentId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CL_Master_State CL_Master_State { get; set; }
    }
}
