//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Bin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_Bin()
        {
            this.CL_Master_Bin1 = new HashSet<CL_Master_Bin>();
        }
    
        public short WarehouseId { get; set; }
        public short BindId { get; set; }
        public string BinCode { get; set; }
        public string BinName { get; set; }
        public byte BinHierarchyId { get; set; }
        public Nullable<short> ParentBindId { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Bin> CL_Master_Bin1 { get; set; }
        public virtual CL_Master_Bin CL_Master_Bin2 { get; set; }
        public virtual CL_Master_Warehouse CL_Master_Warehouse { get; set; }
    }
}
