//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Vehicle_ColdChainRate
    {
        public short VehicleId { get; set; }
        public decimal OutsideCityDryKmpl { get; set; }
        public decimal WithinCityDryKmpl { get; set; }
        public decimal OutsideCityReeferKmpl { get; set; }
        public decimal WithinCityReeferKmpl { get; set; }
        public decimal OutsideCityEmptyKmpl { get; set; }
        public decimal WithinCityEmptyKmpl { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
