//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Route_CityWise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_Route_CityWise()
        {
            this.CL_StandardRouteCharge_Enroute_Expense_History = new HashSet<CL_StandardRouteCharge_Enroute_Expense_History>();
            this.CL_Master_Route_CityWise_Detail = new HashSet<CL_Master_Route_CityWise_Detail>();
        }
    
        public short RouteId { get; set; }
        public string RouteName { get; set; }
        public byte TransportModeId { get; set; }
        public bool RouteCategoryIsLongHaul { get; set; }
        public System.TimeSpan DepartureTime { get; set; }
        public Nullable<int> ControlCityId { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> FromCityId { get; set; }
        public Nullable<int> ToCityId { get; set; }
        public byte TotalTransitTimeHour { get; set; }
        public byte TotalTransitTimeMin { get; set; }
        public decimal DriverAdvanceAmount { get; set; }
        public decimal FuelQuantity { get; set; }
        public Nullable<decimal> StandardFuelInLiters { get; set; }
        public Nullable<decimal> StandardAdvanceAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_StandardRouteCharge_Enroute_Expense_History> CL_StandardRouteCharge_Enroute_Expense_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Route_CityWise_Detail> CL_Master_Route_CityWise_Detail { get; set; }
    }
}
