//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_Route()
        {
            this.CL_Master_Route_Detail = new HashSet<CL_Master_Route_Detail>();
            this.CL_Master_VendorContract_RouteBased = new HashSet<CL_Master_VendorContract_RouteBased>();
        }
    
        public short RouteId { get; set; }
        public string RouteName { get; set; }
        public byte TransportModeId { get; set; }
        public Nullable<byte> RouteCategoryIsLongHaul { get; set; }
        public System.TimeSpan DepartureTime { get; set; }
        public short ControlLocationId { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> OriginLocationId { get; set; }
        public Nullable<short> DestinationLocationId { get; set; }
        public decimal FromAmount { get; set; }
        public decimal ToAmount { get; set; }
    
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Route_Detail> CL_Master_Route_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_VendorContract_RouteBased> CL_Master_VendorContract_RouteBased { get; set; }
    }
}
