//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_VendorContract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_VendorContract()
        {
            this.CL_Master_VendorContract_CityBased = new HashSet<CL_Master_VendorContract_CityBased>();
            this.CL_Master_VendorContract_CrossingBased = new HashSet<CL_Master_VendorContract_CrossingBased>();
            this.CL_Master_VendorContract_DistanceBased = new HashSet<CL_Master_VendorContract_DistanceBased>();
            this.CL_Master_VendorContract_DocketBased = new HashSet<CL_Master_VendorContract_DocketBased>();
            this.CL_Master_VendorContract_FtlBased = new HashSet<CL_Master_VendorContract_FtlBased>();
            this.CL_Master_VendorContract_RouteBased = new HashSet<CL_Master_VendorContract_RouteBased>();
        }
    
        public short ContractId { get; set; }
        public short VendorId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CL_Master_Vendor CL_Master_Vendor { get; set; }
        public virtual CL_Master_VendorContract_BasicInfo CL_Master_VendorContract_BasicInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_VendorContract_CityBased> CL_Master_VendorContract_CityBased { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_VendorContract_CrossingBased> CL_Master_VendorContract_CrossingBased { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_VendorContract_DistanceBased> CL_Master_VendorContract_DistanceBased { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_VendorContract_DocketBased> CL_Master_VendorContract_DocketBased { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_VendorContract_FtlBased> CL_Master_VendorContract_FtlBased { get; set; }
        public virtual CL_Master_VendorContract_LoadingUnloading CL_Master_VendorContract_LoadingUnloading { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_VendorContract_RouteBased> CL_Master_VendorContract_RouteBased { get; set; }
    }
}
