//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_VendorContract_BasicInfo
    {
        public short ContractId { get; set; }
        public string ManualContractId { get; set; }
        public System.DateTime ContractDate { get; set; }
        public short LocationId { get; set; }
        public byte VendorCategory { get; set; }
        public byte ContractCategory { get; set; }
        public string SecurityDepositCheque { get; set; }
        public Nullable<System.DateTime> SecurityDepositDate { get; set; }
        public decimal SecurityDepositAmount { get; set; }
        public string PaymentInterval { get; set; }
        public string PaymentBasis { get; set; }
        public Nullable<short> PaymentLocationId { get; set; }
        public byte ThcMatrixTypeId { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public byte PrsMatrixTypeId { get; set; }
        public byte DrsMatrixTypeId { get; set; }
        public byte CreditDays { get; set; }
        public Nullable<bool> IsTDSApplicable { get; set; }
        public Nullable<decimal> TDSRate { get; set; }
    
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        public virtual CL_Master_Location CL_Master_Location1 { get; set; }
        public virtual CL_Master_VendorContract CL_Master_VendorContract { get; set; }
    }
}
