//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Part_Detail
    {
        public long PartId { get; set; }
        public Nullable<short> PackingTypeId { get; set; }
        public Nullable<decimal> ActualWeight { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> ActualWeightPerQuantity { get; set; }
        public Nullable<short> PackageDimensionsId { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Breadth { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> CftRatio { get; set; }
        public Nullable<decimal> TotalCubic { get; set; }
        public Nullable<decimal> CubicPerQuantity { get; set; }
        public Nullable<short> ConsignorId { get; set; }
        public Nullable<short> ConsigneeId { get; set; }
        public Nullable<bool> IsReverse { get; set; }
    }
}
