//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Vendor_Gst_Detail
    {
        public short VendorId { get; set; }
        public short StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Address { get; set; }
        public string ProvisionalId { get; set; }
        public string GstTinNo { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual CL_Master_Vendor CL_Master_Vendor { get; set; }
    }
}
