//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Warehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_Warehouse()
        {
            this.CL_Master_Bin = new HashSet<CL_Master_Bin>();
            this.CL_Master_Bin_Hierarchy = new HashSet<CL_Master_Bin_Hierarchy>();
            this.CL_Master_User_Warehouse_Mapping = new HashSet<CL_Master_User_Warehouse_Mapping>();
            this.CL_Thc_Docket_Detail = new HashSet<CL_Thc_Docket_Detail>();
            this.CL_Master_Vendor = new HashSet<CL_Master_Vendor>();
        }
    
        public short WarehouseId { get; set; }
        public short LocationId { get; set; }
        public string WarehouseName { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Bin> CL_Master_Bin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Bin_Hierarchy> CL_Master_Bin_Hierarchy { get; set; }
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_User_Warehouse_Mapping> CL_Master_User_Warehouse_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Thc_Docket_Detail> CL_Thc_Docket_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Vendor> CL_Master_Vendor { get; set; }
    }
}
