//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_CustomerContract_RiskMatrix
    {
        public short ContractId { get; set; }
        public decimal FromFreight { get; set; }
        public decimal ToFreight { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public byte RateType { get; set; }
        public bool IsCarrierRisk { get; set; }
        public decimal MinimumChargeAmount { get; set; }
        public decimal MaximumChargeAmount { get; set; }
    
        public virtual CL_Master_CustomerContract CL_Master_CustomerContract { get; set; }
    }
}
