//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_Driver()
        {
            this.CL_Master_Driver_Document = new HashSet<CL_Master_Driver_Document>();
            this.CL_Tripsheet_Header = new HashSet<CL_Tripsheet_Header>();
            this.CL_Tripsheet_Header1 = new HashSet<CL_Tripsheet_Header>();
        }
    
        public short DriverId { get; set; }
        public string DriverName { get; set; }
        public short DriverLocationId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<short> VehicleId { get; set; }
        public string LicenseNo { get; set; }
        public System.DateTime LicenseValidityDate { get; set; }
        public string MobileNo { get; set; }
        public string LicenseIssueBy { get; set; }
        public string ManualDriverCode { get; set; }
        public string DriverFatherName { get; set; }
        public string PermanentAddress { get; set; }
        public short PermanentCityId { get; set; }
        public string PermanentPincode { get; set; }
        public string CurrentAddress { get; set; }
        public short CurrentCityId { get; set; }
        public string CurrentPincode { get; set; }
        public bool UsePermanentAddressAsCurrentAddress { get; set; }
        public string GuarantorName { get; set; }
        public byte CategoryId { get; set; }
        public System.DateTime DoB { get; set; }
        public Nullable<byte> Ethnicity { get; set; }
        public System.DateTime LicenseInitialIssueDate { get; set; }
        public System.DateTime LicenseCurrentIssueDate { get; set; }
        public bool IsLicenseVerified { get; set; }
        public bool IsAddressVerified { get; set; }
        public System.DateTime EntryDate { get; set; }
        public short EntryBy { get; set; }
        public Nullable<System.DateTime> LicenseVerifiedDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool DriverStatus { get; set; }
        public decimal BalanceAmount { get; set; }
        public bool IsAvailable { get; set; }
        public string DriverCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Driver_Document> CL_Master_Driver_Document { get; set; }
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        public virtual CL_Master_Vehicle CL_Master_Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Tripsheet_Header> CL_Tripsheet_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Tripsheet_Header> CL_Tripsheet_Header1 { get; set; }
    }
}
