//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Vendor_Detail
    {
        public short VendorId { get; set; }
        public string Password { get; set; }
        public string PanNo { get; set; }
        public string GstTinNo { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string Address { get; set; }
        public string Remarks { get; set; }
        public bool IsBlackListed { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string TdsCertificate { get; set; }
        public bool IsTDSApplicable { get; set; }
        public decimal TDSRate { get; set; }
        public Nullable<short> CityId { get; set; }
        public bool IsGstApplicable { get; set; }
        public Nullable<long> VendorGstId { get; set; }
        public Nullable<long> CompanyGstId { get; set; }
        public Nullable<short> StateId { get; set; }
        public Nullable<short> TdsAccountId { get; set; }
    
        public virtual CL_Master_Vendor CL_Master_Vendor { get; set; }
    }
}
