//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_VehicleType
    {
        public short VehicleTypeId { get; set; }
        public string Manufacturer { get; set; }
        public string VehicleTypeName { get; set; }
        public string ModelNo { get; set; }
        public string VehicleTypeDescription { get; set; }
        public decimal GrossVehicleWeight { get; set; }
        public decimal UnladenWeight { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public byte FuelTypeId { get; set; }
        public decimal Length { get; set; }
        public decimal Width { get; set; }
        public decimal Height { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
