//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Report_ColumnList
    {
        public byte ReportId { get; set; }
        public string ReportName { get; set; }
        public short FieldId { get; set; }
        public string FieldName { get; set; }
        public string FieldCaption { get; set; }
        public short DisplayOrder { get; set; }
        public string FieldQuery { get; set; }
    }
}
