//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Document_Control
    {
        public byte DocumentTypeId { get; set; }
        public bool UseManualNo { get; set; }
        public bool MandatoryManualNo { get; set; }
        public bool DuplicateManualNo { get; set; }
        public bool UseDcr { get; set; }
        public bool UseBusinessTypeWiseDcr { get; set; }
        public byte DcrLength { get; set; }
        public byte DcrCharacterLength { get; set; }
        public bool UseCharacter { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<byte> CompanyId { get; set; }
    }
}
