//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_ManifestLabourDC_Detail
    {
        public long LabourDCId { get; set; }
        public long ManifestId { get; set; }
        public int NoofDocket { get; set; }
        public int Packages { get; set; }
        public decimal ActualWeight { get; set; }
        public string RateType { get; set; }
        public decimal Rate { get; set; }
        public decimal Amount { get; set; }
    }
}
