//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_SAC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_SAC()
        {
            this.CL_Master_ServiceType_SAC_Mapping = new HashSet<CL_Master_ServiceType_SAC_Mapping>();
            this.CL_Master_ServiceType_SCL_Mapping = new HashSet<CL_Master_ServiceType_SCL_Mapping>();
        }
    
        public byte SacId { get; set; }
        public string SacName { get; set; }
        public string SacCode { get; set; }
        public decimal GstRate { get; set; }
        public bool IsRcm { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_ServiceType_SAC_Mapping> CL_Master_ServiceType_SAC_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_ServiceType_SCL_Mapping> CL_Master_ServiceType_SCL_Mapping { get; set; }
    }
}
