//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Airport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_Airport()
        {
            this.CL_Flight_Schedule_Header = new HashSet<CL_Flight_Schedule_Header>();
            this.CL_Flight_Schedule_Header1 = new HashSet<CL_Flight_Schedule_Header>();
        }
    
        public byte AirportId { get; set; }
        public string AirportNo { get; set; }
        public string AirportName { get; set; }
        public Nullable<int> CityId { get; set; }
        public short AlternateCityId { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public byte CompanyId { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Flight_Schedule_Header> CL_Flight_Schedule_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Flight_Schedule_Header> CL_Flight_Schedule_Header1 { get; set; }
    }
}
