//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_BillFormat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_BillFormat()
        {
            this.CL_Master_CustomerBillFormat = new HashSet<CL_Master_CustomerBillFormat>();
        }
    
        public byte FormatId { get; set; }
        public string Description { get; set; }
        public string DocumentName { get; set; }
        public string ReportFileName { get; set; }
        public string ParameterList { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_CustomerBillFormat> CL_Master_CustomerBillFormat { get; set; }
    }
}
