//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_General_Rule_Values
    {
        public int ID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> RuleID { get; set; }
        public string RuleCode { get; set; }
        public string ValueDescription { get; set; }
    }
}
