//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_CustomerContract_DefineChargeMatrix
    {
        public short ContractId { get; set; }
        public bool IsBooking { get; set; }
        public byte BaseOn { get; set; }
        public byte BaseCode { get; set; }
        public byte ChargeCode { get; set; }
        public bool UseTransportMode { get; set; }
        public bool UseRateType { get; set; }
        public bool UseFrom { get; set; }
        public bool UseTo { get; set; }
        public string SlabType { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public byte ChargeBase { get; set; }
        public bool UseFtlType { get; set; }
        public bool UseConsignor { get; set; }
        public bool UseConsignee { get; set; }
        public bool UsePartNo { get; set; }
        public bool UseBillingCode { get; set; }
    
        public virtual CL_Master_CustomerContract CL_Master_CustomerContract { get; set; }
    }
}
