//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Vehicle_Detail
    {
        public short VehicleId { get; set; }
        public Nullable<byte> NoOfDrivers { get; set; }
        public bool IsGpsEnabled { get; set; }
        public string GpsDeviceId { get; set; }
        public string VehicleBroker { get; set; }
        public Nullable<byte> NoOfTyres { get; set; }
        public string RcBookNo { get; set; }
        public string RegistrationNo { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string InsuranceNo { get; set; }
        public System.DateTime InsuranceIssueDate { get; set; }
        public System.DateTime InsuranceExpiryDate { get; set; }
        public string FitnessCertificateNo { get; set; }
        public System.DateTime FitnessCertificateIssueDate { get; set; }
        public string NationalPermitNo { get; set; }
        public System.DateTime NationalPermitIssueDate { get; set; }
        public System.DateTime NationalPermitExpiryDate { get; set; }
        public string PollutionCertificateNo { get; set; }
        public System.DateTime PollutionCertificateIssueDate { get; set; }
        public System.DateTime PollutionCertificateExpiryDate { get; set; }
        public string AuthorisationNo { get; set; }
        public Nullable<System.DateTime> AuthorisationIssueDate { get; set; }
        public Nullable<System.DateTime> AuthorisationExpiryDate { get; set; }
        public string RoadTaxNo { get; set; }
        public Nullable<System.DateTime> RoadTaxIssueDate { get; set; }
        public Nullable<System.DateTime> RoadTaxExpiryDate { get; set; }
        public System.DateTime AttachingDate { get; set; }
        public string ChasisNo { get; set; }
        public string EngineNo { get; set; }
        public string RtoName { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string LocalPermitNo { get; set; }
        public Nullable<System.DateTime> LocalPermitIssueDate { get; set; }
        public Nullable<System.DateTime> LocalPermitExpiryDate { get; set; }
        public Nullable<System.DateTime> FitnessCertificateExpiryDate { get; set; }
        public decimal VehicleMileage { get; set; }
    
        public virtual CL_Master_Vehicle CL_Master_Vehicle { get; set; }
    }
}
