//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Mr_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Mr_Header()
        {
            this.CL_Mr_Bill_Detail = new HashSet<CL_Mr_Bill_Detail>();
            this.CL_Mr_Docket_Charge_Detail = new HashSet<CL_Mr_Docket_Charge_Detail>();
        }
    
        public long MrId { get; set; }
        public string MrNo { get; set; }
        public string ManualMrNo { get; set; }
        public System.DateTime MrDate { get; set; }
        public System.TimeSpan MrTime { get; set; }
        public Nullable<System.DateTime> MrDateTime { get; set; }
        public byte MrTypeId { get; set; }
        public short LocationId { get; set; }
        public short PartyId { get; set; }
        public string PartyName { get; set; }
        public Nullable<long> DocketId { get; set; }
        public string DocketSuffix { get; set; }
        public Nullable<short> DeliverPartyId { get; set; }
        public string DeliverPartyName { get; set; }
        public decimal MrSubTotal { get; set; }
        public decimal MrTaxTotal { get; set; }
        public decimal MrGrandTotal { get; set; }
        public decimal MrDifferenceAmount { get; set; }
        public decimal MrCollectionAmount { get; set; }
        public Nullable<short> MrCollectionLocationId { get; set; }
        public Nullable<short> TdsAccountId { get; set; }
        public decimal TdsAmount { get; set; }
        public bool IsFinalized { get; set; }
        public Nullable<System.DateTime> FinalizedDate { get; set; }
        public bool IsBillMr { get; set; }
        public bool IsMrClose { get; set; }
        public Nullable<System.DateTime> MrCloseDate { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public Nullable<short> CancelBy { get; set; }
        public string Remarks { get; set; }
        public bool IsByCash { get; set; }
        public Nullable<long> ChequeId { get; set; }
        public Nullable<bool> IsDeliveredByConsignee { get; set; }
        public Nullable<bool> IsDeliveredFromMaster { get; set; }
        public Nullable<byte> WarehouseId { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public byte CompanyId { get; set; }
        public string GstTinNo { get; set; }
        public Nullable<long> VoucherId { get; set; }
        public Nullable<bool> isPartial { get; set; }
        public Nullable<long> BillId { get; set; }
    
        public virtual CL_Cheque_Detail CL_Cheque_Detail { get; set; }
        public virtual CL_Docket CL_Docket { get; set; }
        public virtual CL_Master_Company CL_Master_Company { get; set; }
        public virtual CL_Master_Customer CL_Master_Customer { get; set; }
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Mr_Bill_Detail> CL_Mr_Bill_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Mr_Docket_Charge_Detail> CL_Mr_Docket_Charge_Detail { get; set; }
    }
}
