//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Tax_Detail
    {
        public short Id { get; set; }
        public byte TransportModeId { get; set; }
        public byte ServiceTypeId { get; set; }
        public decimal RebatePercentage { get; set; }
        public decimal ExceedAmount { get; set; }
    
        public virtual CL_Master_Tax CL_Master_Tax { get; set; }
    }
}
