//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_State
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_State()
        {
            this.CL_Master_City = new HashSet<CL_Master_City>();
            this.CL_Master_Gst = new HashSet<CL_Master_Gst>();
            this.CL_Master_State_Document = new HashSet<CL_Master_State_Document>();
        }
    
        public byte CountryId { get; set; }
        public short StateId { get; set; }
        public string StateName { get; set; }
        public bool IsServiceTaxExempted { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsState { get; set; }
        public Nullable<byte> StateCode { get; set; }
        public Nullable<bool> IsUnionTerritory { get; set; }
        public string API_USER { get; set; }
        public string API_PASSWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_City> CL_Master_City { get; set; }
        public virtual CL_Master_Country CL_Master_Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Gst> CL_Master_Gst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_State_Document> CL_Master_State_Document { get; set; }
    }
}
