//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_MilkRunsheetBill_Detail
    {
        public long TripsheetBillId { get; set; }
        public long TripsheetId { get; set; }
        public decimal FixedAmount { get; set; }
        public decimal FixedKm { get; set; }
        public decimal VariableRate { get; set; }
        public decimal KmRun { get; set; }
        public decimal ActualAmount { get; set; }
        public decimal ExtraAmount { get; set; }
        public decimal NetAmount { get; set; }
        public decimal GstRate { get; set; }
        public decimal Igst { get; set; }
        public decimal Cgst { get; set; }
        public decimal Sgst { get; set; }
        public decimal GstTotal { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<decimal> TotalHolidayAmount { get; set; }
        public Nullable<decimal> TotalWorkingHourAmount { get; set; }
        public Nullable<decimal> OtherFixedAmount { get; set; }
        public Nullable<decimal> StateTax { get; set; }
        public Nullable<decimal> ParkingCharge { get; set; }
        public Nullable<decimal> LabourCharge { get; set; }
        public Nullable<decimal> VariableBaseAmtPerTrip { get; set; }
        public Nullable<decimal> TotalTripFSCAmount { get; set; }
        public Nullable<decimal> TollAmount { get; set; }
        public Nullable<decimal> AdditionalKM { get; set; }
        public Nullable<decimal> AdditionalAmountKM { get; set; }
        public Nullable<decimal> OtherCharge { get; set; }
    }
}
