//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Master_Product()
        {
            this.CL_Master_Product_Customer_Mapping = new HashSet<CL_Master_Product_Customer_Mapping>();
            this.CL_Order_Detail = new HashSet<CL_Order_Detail>();
        }
    
        public byte CompanyId { get; set; }
        public int ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public byte UomId { get; set; }
        public Nullable<decimal> UomQuantity { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Breadth { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> ActualWeight { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool IsSerialNumber { get; set; }
        public Nullable<bool> IsSingle { get; set; }
        public decimal ChargeWeight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Product_Customer_Mapping> CL_Master_Product_Customer_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Order_Detail> CL_Order_Detail { get; set; }
    }
}
