//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Route_CityWise_Detail
    {
        public short RouteId { get; set; }
        public Nullable<int> CityId { get; set; }
        public decimal Distance { get; set; }
        public byte TransitTimeHour { get; set; }
        public byte TransitTimeMin { get; set; }
        public byte StoppageTimeHour { get; set; }
        public byte StoppageTimeMin { get; set; }
        public byte RouteIndex { get; set; }
    
        public virtual CL_Master_Route_CityWise CL_Master_Route_CityWise { get; set; }
    }
}
