//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_City
    {
        public short StateId { get; set; }
        public byte ZoneId { get; set; }
        public int CityId { get; set; }
        public string CityName { get; set; }
        public bool IsPermitRequired { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool IsOdaApplicable { get; set; }
        public decimal OdaKm { get; set; }
    
        public virtual CL_Master_Zone CL_Master_Zone { get; set; }
        public virtual CL_Master_State CL_Master_State { get; set; }
    }
}
