//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Issue_History
    {
        public long HistoryId { get; set; }
        public long IssueId { get; set; }
        public byte ClientId { get; set; }
        public System.DateTime IssueDateTime { get; set; }
        public short MainMenuId { get; set; }
        public short ParentMenuId { get; set; }
        public short ChildMenuId { get; set; }
        public string IssueDescription { get; set; }
        public byte IssueTypeId { get; set; }
        public string IssueImage { get; set; }
        public byte IssuePriorityId { get; set; }
        public byte IssueRaisedById { get; set; }
        public byte IssueStatus { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string ResolvedDocument { get; set; }
        public string Comment { get; set; }
        public Nullable<byte> ResolvedById { get; set; }
        public Nullable<System.DateTime> ResolvedDateTime { get; set; }
        public string ApprovalComment { get; set; }
        public Nullable<byte> ApprovedById { get; set; }
        public Nullable<System.DateTime> ApprovedDateTime { get; set; }
    }
}
