//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Product_Customer_Mapping
    {
        public int ProductId { get; set; }
        public short ConsignorId { get; set; }
        public short ConsigneeId { get; set; }
        public bool IsActive { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public byte CompanyId { get; set; }
    
        public virtual CL_Master_Customer CL_Master_Customer { get; set; }
        public virtual CL_Master_Customer CL_Master_Customer1 { get; set; }
        public virtual CL_Master_Product CL_Master_Product { get; set; }
    }
}
