//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_AccountOpening_Party
    {
        public string FinYear { get; set; }
        public byte PartyType { get; set; }
        public short PartyId { get; set; }
        public short LocationId { get; set; }
        public short AccountId { get; set; }
        public byte CompanyId { get; set; }
        public decimal DebitAmount { get; set; }
        public decimal CreditAmount { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual CL_Master_Account CL_Master_Account { get; set; }
        public virtual CL_Master_Location CL_Master_Location { get; set; }
    }
}
