//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_User_Warehouse_Mapping
    {
        public short UserId { get; set; }
        public short WarehouseId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual CL_Master_User CL_Master_User { get; set; }
        public virtual CL_Master_Warehouse CL_Master_Warehouse { get; set; }
    }
}
