//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Fuel_Card
    {
        public byte FuelCardId { get; set; }
        public string ManualFuelCardNo { get; set; }
        public short VendorId { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public short VehicleId { get; set; }
        public Nullable<byte> FuelTypeId { get; set; }
        public Nullable<byte> FuelBrandId { get; set; }
        public bool IsActive { get; set; }
        public short AccountId { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual CL_Master_Account CL_Master_Account { get; set; }
        public virtual CL_Master_Fuel_Brand CL_Master_Fuel_Brand { get; set; }
        public virtual CL_Master_Vehicle CL_Master_Vehicle { get; set; }
        public virtual CL_Master_Vendor CL_Master_Vendor { get; set; }
    }
}
