//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_RoleBasedMenu_Access
    {
        public byte RoleId { get; set; }
        public byte UserId { get; set; }
        public short MenuId { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public byte CompanyId { get; set; }
    
        public virtual CL_Master_Menu CL_Master_Menu { get; set; }
        public virtual CL_Master_Role CL_Master_Role { get; set; }
    }
}
