//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_Fields
    {
        public byte ModuleId { get; set; }
        public string FieldName { get; set; }
        public string FieldCaption { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsMandatory { get; set; }
        public bool IsEditable { get; set; }
        public bool UseFieldCaptionEdit { get; set; }
        public bool UseMandatoryEdit { get; set; }
    }
}
