//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Master_CityWiseFuelRate_History
    {
        public int SrNo { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<short> VendorId { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<short> EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDateTime { get; set; }
    
        public virtual CL_Master_User CL_Master_User { get; set; }
        public virtual CL_Master_User CL_Master_User1 { get; set; }
        public virtual CL_Master_Vendor CL_Master_Vendor { get; set; }
        public virtual CL_Master_Vendor CL_Master_Vendor1 { get; set; }
    }
}
