//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Order_Detail
    {
        public byte CompanyId { get; set; }
        public short WarehouseId { get; set; }
        public long OrderId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int ProductId { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual CL_Master_Product CL_Master_Product { get; set; }
    }
}
