//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Order_Header
    {
        public byte CompanyId { get; set; }
        public short WarehouseId { get; set; }
        public long OrderId { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.TimeSpan OrderTime { get; set; }
        public Nullable<System.DateTime> OrderDateTime { get; set; }
        public short CustomerId { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public short BillToAddressId { get; set; }
        public string BillToAddress1 { get; set; }
        public string BillToAddress2 { get; set; }
        public short BillToCityId { get; set; }
        public string BillToPincode { get; set; }
        public string BillToMobileNo { get; set; }
        public string BillToEmailId { get; set; }
        public string BillToTinNo { get; set; }
        public string BillToCstNo { get; set; }
        public short ShipToAddressId { get; set; }
        public string ShipToAddress1 { get; set; }
        public string ShipToAddress2 { get; set; }
        public short ShipToCityId { get; set; }
        public string ShipToPincode { get; set; }
        public string ShipToMobileNo { get; set; }
        public string ShipToEmailId { get; set; }
        public string ShipToTinNo { get; set; }
        public string ShipToCstNo { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool PickStatus { get; set; }
        public bool DispatchStatus { get; set; }
    }
}
