//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Pod
    {
        public long PodId { get; set; }
        public byte DocumentTypeId { get; set; }
        public long DocumentId { get; set; }
        public string ManualNo { get; set; }
        public string DocumentName { get; set; }
        public short LocationId { get; set; }
        public Nullable<bool> IsForward { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public byte CompanyId { get; set; }
        public string Signature { get; set; }
    
        public virtual CL_Master_Location CL_Master_Location { get; set; }
    }
}
