//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_PO_Grn_Detail
    {
        public long GrnId { get; set; }
        public long PoId { get; set; }
        public byte SkuId { get; set; }
        public int Quantity { get; set; }
        public decimal Rate { get; set; }
        public int ReceivedQuantity { get; set; }
        public int PendingQuantity { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual CL_Master_SKU CL_Master_SKU { get; set; }
        public virtual CL_PO_Grn_Header CL_PO_Grn_Header { get; set; }
        public virtual CL_PurchaseOrder_Header CL_PurchaseOrder_Header { get; set; }
    }
}
