//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Pfm_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Pfm_Header()
        {
            this.CL_Pfm_Detail = new HashSet<CL_Pfm_Detail>();
        }
    
        public long PfmId { get; set; }
        public string PfmNo { get; set; }
        public System.DateTime PfmDate { get; set; }
        public System.TimeSpan PfmTime { get; set; }
        public Nullable<System.DateTime> PfmDateTime { get; set; }
        public string ManualPfmNo { get; set; }
        public short LocationId { get; set; }
        public bool ForwardType { get; set; }
        public short ForwardToId { get; set; }
        public string CourierName { get; set; }
        public string WayBillNo { get; set; }
        public System.DateTime WayBillDate { get; set; }
        public bool IsAcknowledge { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public byte CompanyId { get; set; }
        public byte DocumentTypeId { get; set; }
        public Nullable<System.DateTime> AcknowledgeDate { get; set; }
        public Nullable<short> AcknowledgeBy { get; set; }
        public string ReceivedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Pfm_Detail> CL_Pfm_Detail { get; set; }
    }
}
