//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_PO_Grn_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_PO_Grn_Header()
        {
            this.CL_PO_Grn_Detail = new HashSet<CL_PO_Grn_Detail>();
        }
    
        public long GrnId { get; set; }
        public string GrnNo { get; set; }
        public string ManualGrnNo { get; set; }
        public System.DateTime GrnDate { get; set; }
        public short LocationId { get; set; }
        public long PoId { get; set; }
        public string Remarks { get; set; }
        public decimal Amount { get; set; }
        public short ReceivedBy { get; set; }
        public System.DateTime ReceivedDate { get; set; }
    
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_PO_Grn_Detail> CL_PO_Grn_Detail { get; set; }
        public virtual CL_PurchaseOrder_Header CL_PurchaseOrder_Header { get; set; }
    }
}
