//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Repacking_Detail
    {
        public long RepackingId { get; set; }
        public long GrnId { get; set; }
        public int ProductId { get; set; }
        public decimal GrnQuantity { get; set; }
        public decimal RepackingQuantity { get; set; }
        public decimal ApproveQuantity { get; set; }
        public decimal RejectQuantity { get; set; }
        public byte RejectReason { get; set; }
        public string Remarks { get; set; }
    
        public virtual CL_Repacking_Header CL_Repacking_Header { get; set; }
    }
}
