//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_SpareRequest_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_SpareRequest_Header()
        {
            this.CL_SpareRequest_Detail = new HashSet<CL_SpareRequest_Detail>();
        }
    
        public long SpareRequestId { get; set; }
        public string SpareRequestNo { get; set; }
        public System.DateTime SpareRequestDate { get; set; }
        public long JobOrderId { get; set; }
        public short LocationId { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual CL_JobOrder_Header CL_JobOrder_Header { get; set; }
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_SpareRequest_Detail> CL_SpareRequest_Detail { get; set; }
    }
}
