//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Stock_SerialWise
    {
        public byte CompanyId { get; set; }
        public short WarehouseId { get; set; }
        public int SkuId { get; set; }
        public string FirstSerialNo { get; set; }
        public string SecondSerialNo { get; set; }
        public long GrnId { get; set; }
        public Nullable<short> BinId { get; set; }
        public Nullable<long> PutAwayId { get; set; }
        public Nullable<long> DispatchId { get; set; }
    }
}
