//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Thc_Header_History
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Thc_Header_History()
        {
            this.CL_Thc_Charge_Detail_History = new HashSet<CL_Thc_Charge_Detail_History>();
            this.CL_Thc_Docket_Detail_History = new HashSet<CL_Thc_Docket_Detail_History>();
            this.CL_Thc_Manifest_Detail_History = new HashSet<CL_Thc_Manifest_Detail_History>();
            this.CL_Thc_Summary_History = new HashSet<CL_Thc_Summary_History>();
        }
    
        public long HistoryId { get; set; }
        public long ThcId { get; set; }
        public string ThcNo { get; set; }
        public System.DateTime ThcDate { get; set; }
        public System.TimeSpan ThcTime { get; set; }
        public Nullable<System.DateTime> ThcDateTime { get; set; }
        public string ManualThcNo { get; set; }
        public byte TransportModeId { get; set; }
        public short RouteId { get; set; }
        public short FromLocationId { get; set; }
        public short ToLocationId { get; set; }
        public short CurrentLocationId { get; set; }
        public Nullable<short> FromCityId { get; set; }
        public Nullable<short> ToCityId { get; set; }
        public bool IsEmptyVehicle { get; set; }
        public bool IsAdhoc { get; set; }
        public Nullable<short> VendorId { get; set; }
        public string VendorName { get; set; }
        public string SupplierName { get; set; }
        public string SupplierMobileNo { get; set; }
        public Nullable<short> VehicleId { get; set; }
        public string VehicleNo { get; set; }
        public Nullable<short> VehicleTypeId { get; set; }
        public Nullable<short> FtlTypeId { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string EngineNo { get; set; }
        public string ChassisNo { get; set; }
        public string RcBookNo { get; set; }
        public Nullable<System.DateTime> InsuranceValidityDate { get; set; }
        public Nullable<System.DateTime> FitnessValidityDate { get; set; }
        public Nullable<System.DateTime> PermitValidityDate { get; set; }
        public string FirstDriverName { get; set; }
        public string FirstDriverMobileNo { get; set; }
        public string FirstDriverLicenseNo { get; set; }
        public string FirstDriverLicenseIssueBy { get; set; }
        public Nullable<System.DateTime> FirstDriverLicenseValidityDate { get; set; }
        public string SecondDriverName { get; set; }
        public string SecondDriverMobileNo { get; set; }
        public string SecondDriverLicenseNo { get; set; }
        public string SecondDriverLicenseIssueBy { get; set; }
        public Nullable<System.DateTime> SecondDriverLicenseValidityDate { get; set; }
        public Nullable<byte> AirportId { get; set; }
        public Nullable<byte> AirlineId { get; set; }
        public Nullable<byte> FlightId { get; set; }
        public string AwbNo { get; set; }
        public string TrainName { get; set; }
        public string TrainNo { get; set; }
        public decimal ContractAmount { get; set; }
        public decimal AdvanceAmount { get; set; }
        public short BalanceLocationId { get; set; }
        public Nullable<short> AdvanceLocationId { get; set; }
        public byte FinacialStatus { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public byte CompanyId { get; set; }
        public decimal OtherAmount { get; set; }
        public Nullable<short> CancelBy { get; set; }
        public Nullable<long> TripsheetId { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<decimal> TotalActualWeight { get; set; }
        public Nullable<decimal> KantaWeight { get; set; }
        public string SlipNo { get; set; }
        public string ReasonForWeightLoss { get; set; }
        public Nullable<short> TDSRuleId { get; set; }
        public Nullable<decimal> TDSAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Thc_Charge_Detail_History> CL_Thc_Charge_Detail_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Thc_Docket_Detail_History> CL_Thc_Docket_Detail_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Thc_Manifest_Detail_History> CL_Thc_Manifest_Detail_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Thc_Summary_History> CL_Thc_Summary_History { get; set; }
    }
}
