//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Tripsheet_CheckList
    {
        public long TripsheetId { get; set; }
        public byte CheckListId { get; set; }
        public string Remarks { get; set; }
    
        public virtual CL_Tripsheet_Header CL_Tripsheet_Header { get; set; }
    }
}
