//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Tripsheet_VehicleLog_Detail
    {
        public long TripsheetId { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public int StartKm { get; set; }
        public int EndKm { get; set; }
        public byte Category { get; set; }
        public int ProductId { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public int KmRun { get; set; }
        public string TransitTime { get; set; }
        public string IdleTime { get; set; }
        public Nullable<bool> isBilled { get; set; }
        public Nullable<bool> IsDeclareHoliday { get; set; }
        public Nullable<decimal> StateTax { get; set; }
        public Nullable<decimal> ParkingCharge { get; set; }
        public Nullable<decimal> LabourCharge { get; set; }
    }
}
