//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Tripsheet_Advance
    {
        public long TripsheetId { get; set; }
        public short LocationId { get; set; }
        public string Place { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal Amount { get; set; }
        public string PaidBy { get; set; }
        public long VoucherId { get; set; }
        public Nullable<short> AdvanceCardId { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public Nullable<short> CancelBy { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public string Remarks { get; set; }
    
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        public virtual CL_Tripsheet_Header CL_Tripsheet_Header { get; set; }
        public virtual CL_Voucher_Detail CL_Voucher_Detail { get; set; }
    }
}
