//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Thc_Docket_Detail_History
    {
        public long HistoryId { get; set; }
        public long ThcId { get; set; }
        public Nullable<long> ManifestId { get; set; }
        public long DocketId { get; set; }
        public string DocketSuffix { get; set; }
        public int ArrivalPackages { get; set; }
        public decimal ArrivalWeight { get; set; }
        public byte ArrivalConditionId { get; set; }
        public Nullable<short> WarehouseId { get; set; }
        public byte DeliveryProcessId { get; set; }
        public short LoadLocationId { get; set; }
        public Nullable<short> UnloadLocationId { get; set; }
    
        public virtual CL_Thc_Header_History CL_Thc_Header_History { get; set; }
    }
}
