//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Tripsheet_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_Tripsheet_Header()
        {
            this.CL_CustomerBill_Tripsheet_Detail = new HashSet<CL_CustomerBill_Tripsheet_Detail>();
            this.CL_Tripsheet_Advance = new HashSet<CL_Tripsheet_Advance>();
            this.CL_Tripsheet_CheckList = new HashSet<CL_Tripsheet_CheckList>();
            this.CL_Tripsheet_Enroute_Expense = new HashSet<CL_Tripsheet_Enroute_Expense>();
            this.CL_Tripsheet_ExpectedDriverAdvance = new HashSet<CL_Tripsheet_ExpectedDriverAdvance>();
            this.CL_FuelRequest = new HashSet<CL_FuelRequest>();
            this.CL_Tripsheet_DriverSettlement = new HashSet<CL_Tripsheet_DriverSettlement>();
            this.CL_Tripsheet_FuelSlip = new HashSet<CL_Tripsheet_FuelSlip>();
            this.CL_Tripsheet_Lane_Detail = new HashSet<CL_Tripsheet_Lane_Detail>();
            this.CL_Tripsheet_Oil_Expense = new HashSet<CL_Tripsheet_Oil_Expense>();
            this.CL_Tripsheet_Thc_Detail = new HashSet<CL_Tripsheet_Thc_Detail>();
            this.CL_Master_Card = new HashSet<CL_Master_Card>();
            this.CL_Docket = new HashSet<CL_Docket>();
        }
    
        public byte CompanyId { get; set; }
        public long TripsheetId { get; set; }
        public string TripsheetNo { get; set; }
        public System.DateTime TripsheetDate { get; set; }
        public System.TimeSpan TripsheetTime { get; set; }
        public Nullable<System.DateTime> TripsheetDateTime { get; set; }
        public string ManualTripsheetNo { get; set; }
        public short StartLocationId { get; set; }
        public short EndLocationId { get; set; }
        public byte Category { get; set; }
        public Nullable<byte> SubCategory { get; set; }
        public Nullable<short> CustomerId { get; set; }
        public Nullable<short> VehicleId { get; set; }
        public Nullable<int> StartKm { get; set; }
        public Nullable<int> FromCityId { get; set; }
        public Nullable<int> ToCityId { get; set; }
        public Nullable<int> RouteId { get; set; }
        public decimal DriverBalance { get; set; }
        public bool IsThcAttached { get; set; }
        public bool IsFuelSlipProvided { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string FirstDriverName { get; set; }
        public string FirstDriverMobileNo { get; set; }
        public string FirstDriverLicenseNo { get; set; }
        public string FirstDriverLicenseIssueBy { get; set; }
        public System.DateTime FirstDriverLicenseValidityDate { get; set; }
        public string SecondDriverName { get; set; }
        public string SecondDriverMobileNo { get; set; }
        public string SecondDriverLicenseNo { get; set; }
        public string SecondDriverLicenseIssueBy { get; set; }
        public Nullable<System.DateTime> SecondDriverLicenseValidityDate { get; set; }
        public byte TransitTimeHour { get; set; }
        public byte TransitTimeMinute { get; set; }
        public string CheckListCheckedBy { get; set; }
        public Nullable<System.DateTime> CheckListCheckedDate { get; set; }
        public string CheckListApprovedBy { get; set; }
        public Nullable<System.DateTime> CheckListApprovedDate { get; set; }
        public int EndKm { get; set; }
        public bool OpCloseStatus { get; set; }
        public bool FinCloseStatus { get; set; }
        public Nullable<System.DateTime> OpCloseDateTime { get; set; }
        public Nullable<System.DateTime> FinCloseDateTime { get; set; }
        public string PreparedBy { get; set; }
        public string CheckedBy { get; set; }
        public string ApprovedBy { get; set; }
        public string AuditedBy { get; set; }
        public bool DriverSettlementStatus { get; set; }
        public Nullable<short> FirstDriverId { get; set; }
        public Nullable<short> SecondDriverId { get; set; }
        public bool IsBilled { get; set; }
        public bool UseFuelCard { get; set; }
        public bool UseCashCard { get; set; }
        public Nullable<short> CancelBy { get; set; }
        public decimal ExpectedAmount { get; set; }
        public decimal PendingAmount { get; set; }
        public Nullable<decimal> FastTagTransactionFare { get; set; }
        public Nullable<bool> IsFastTagBillGenerated { get; set; }
        public Nullable<long> FastTagBillNo { get; set; }
        public Nullable<bool> IsMilkRunBilled { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CustomerBill_Tripsheet_Detail> CL_CustomerBill_Tripsheet_Detail { get; set; }
        public virtual CL_Master_Customer CL_Master_Customer { get; set; }
        public virtual CL_Master_Driver CL_Master_Driver { get; set; }
        public virtual CL_Master_Driver CL_Master_Driver1 { get; set; }
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        public virtual CL_Master_Location CL_Master_Location1 { get; set; }
        public virtual CL_Master_Vehicle CL_Master_Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Tripsheet_Advance> CL_Tripsheet_Advance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Tripsheet_CheckList> CL_Tripsheet_CheckList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Tripsheet_Enroute_Expense> CL_Tripsheet_Enroute_Expense { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Tripsheet_ExpectedDriverAdvance> CL_Tripsheet_ExpectedDriverAdvance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_FuelRequest> CL_FuelRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Tripsheet_DriverSettlement> CL_Tripsheet_DriverSettlement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Tripsheet_FuelSlip> CL_Tripsheet_FuelSlip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Tripsheet_Lane_Detail> CL_Tripsheet_Lane_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Tripsheet_Oil_Expense> CL_Tripsheet_Oil_Expense { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Tripsheet_Thc_Detail> CL_Tripsheet_Thc_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Master_Card> CL_Master_Card { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_Docket> CL_Docket { get; set; }
    }
}
