//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_TripsheetBill_Header
    {
        public byte CompanyId { get; set; }
        public short CustomerId { get; set; }
        public long TripsheetBillId { get; set; }
        public string TripsheetBillNo { get; set; }
        public System.DateTime TripsheetBillDate { get; set; }
        public System.TimeSpan TripsheetBillTime { get; set; }
        public System.DateTime TripsheetBillDueDate { get; set; }
        public string ManualTripsheetNo { get; set; }
        public Nullable<int> ServiceType { get; set; }
        public Nullable<decimal> GstRate { get; set; }
        public Nullable<bool> IsExemptGst { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Sgst { get; set; }
        public decimal Cgst { get; set; }
        public decimal Igst { get; set; }
        public decimal GstTotal { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<short> LocationId { get; set; }
        public string EntryBy { get; set; }
    }
}
