//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Tripsheet_Thc_Detail
    {
        public long TripsheetId { get; set; }
        public Nullable<int> FromCityId { get; set; }
        public Nullable<int> ToCityId { get; set; }
        public string ThcNo { get; set; }
        public System.DateTime ThcDate { get; set; }
        public decimal FreightAmount { get; set; }
        public decimal LabourCharge { get; set; }
        public decimal OtherCharge { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual CL_Tripsheet_Header CL_Tripsheet_Header { get; set; }
    }
}
