//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Tripsheet_DriverSettlement
    {
        public long TripsheetId { get; set; }
        public System.DateTime SettlementDate { get; set; }
        public Nullable<decimal> TotalAdvance { get; set; }
        public decimal TotalExpense { get; set; }
        public decimal NetAmount { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal ReceivedAmount { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public Nullable<long> VoucherId { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Remarks { get; set; }
        public decimal TotalEnrouteExpense { get; set; }
        public decimal TotalOilExpenseCash { get; set; }
        public decimal TotalOilExpenseCard { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public Nullable<short> CancelBy { get; set; }
        public bool IsCancel { get; set; }
    
        public virtual CL_Tripsheet_Header CL_Tripsheet_Header { get; set; }
        public virtual CL_Voucher_Detail CL_Voucher_Detail { get; set; }
    }
}
