//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Thc_Manifest_LoadUnload
    {
        public long LoadunloadId { get; set; }
        public long ThcId { get; set; }
        public long ManifestId { get; set; }
        public long Locationid { get; set; }
        public Nullable<bool> load { get; set; }
        public Nullable<System.DateTime> loadDate { get; set; }
        public Nullable<bool> Unload { get; set; }
        public Nullable<System.DateTime> UnloadDate { get; set; }
        public int TotalPackages { get; set; }
        public decimal TotalActualWeight { get; set; }
        public Nullable<bool> isProcessed { get; set; }
        public string LoadUnloadNo { get; set; }
    }
}
