//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Tripsheet_ExpectedDriverAdvance
    {
        public long TripsheetId { get; set; }
        public short LocationId { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        public virtual CL_Tripsheet_Header CL_Tripsheet_Header { get; set; }
    }
}
