//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_VendorPayment_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_VendorPayment_Header()
        {
            this.CL_VendorPayment_Detail = new HashSet<CL_VendorPayment_Detail>();
        }
    
        public long PaymentId { get; set; }
        public long VoucherId { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public Nullable<short> CancelBy { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public byte CompanyId { get; set; }
        public string PaymentNo { get; set; }
        public short LocationId { get; set; }
        public byte PaymentTypeId { get; set; }
        public string CancelReason { get; set; }
        public string BillPaymentRemarks { get; set; }
        public Nullable<short> VendorId { get; set; }
    
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_VendorPayment_Detail> CL_VendorPayment_Detail { get; set; }
        public virtual CL_Voucher_Detail CL_Voucher_Detail { get; set; }
    }
}
