//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Vehicle_Status_History
    {
        public string VehicleNo { get; set; }
        public string VehicleStatus { get; set; }
        public System.DateTime StatusDateTime { get; set; }
        public System.DateTime EntryDate { get; set; }
    }
}
