//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_VendorBill_FastTagDetail
    {
        public long BillId { get; set; }
        public short VendorId { get; set; }
        public short VendorGstStateId { get; set; }
        public short VendorLocationId { get; set; }
        public short VendorCityId { get; set; }
        public short VendorGstId { get; set; }
        public short CompanyId { get; set; }
        public short CompanyGstStateId { get; set; }
        public short CompanyLocationId { get; set; }
        public short CompanyCityId { get; set; }
        public Nullable<bool> IsInterState { get; set; }
        public Nullable<bool> IsGstRegistered { get; set; }
        public byte SacId { get; set; }
        public decimal GstRate { get; set; }
        public decimal GrossAmount { get; set; }
        public decimal GstAmount { get; set; }
        public decimal Igst { get; set; }
        public decimal Cgst { get; set; }
        public decimal Sgst { get; set; }
        public decimal Ugst { get; set; }
        public decimal IgstPercentage { get; set; }
        public decimal CgstPercentage { get; set; }
        public decimal SgstPercentage { get; set; }
        public decimal UgstPercentage { get; set; }
        public decimal NetPayableAmount { get; set; }
        public Nullable<System.DateTime> EntryDateTime { get; set; }
    }
}
