//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_VendorBill_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_VendorBill_Header()
        {
            this.CL_VendorBill_OtherDetail = new HashSet<CL_VendorBill_OtherDetail>();
            this.CL_VendorBill_Charge_Detail = new HashSet<CL_VendorBill_Charge_Detail>();
            this.CL_VendorBill_Detail = new HashSet<CL_VendorBill_Detail>();
            this.CL_VendorBill_Tax_Detail = new HashSet<CL_VendorBill_Tax_Detail>();
        }
    
        public long BillId { get; set; }
        public string BillNo { get; set; }
        public string ManualBillNo { get; set; }
        public short LocationId { get; set; }
        public System.DateTime BillDate { get; set; }
        public System.TimeSpan BillTime { get; set; }
        public Nullable<System.DateTime> BillDateTime { get; set; }
        public Nullable<System.DateTime> BillDueDate { get; set; }
        public byte BillType { get; set; }
        public short VendorId { get; set; }
        public bool IsFinalize { get; set; }
        public Nullable<short> FinalizeBy { get; set; }
        public Nullable<System.DateTime> FinalizeDate { get; set; }
        public Nullable<byte> GstTypeId { get; set; }
        public Nullable<short> VendorGstStateId { get; set; }
        public Nullable<long> VendorGstId { get; set; }
        public Nullable<short> CompanyGstStateId { get; set; }
        public Nullable<long> CompanyGstId { get; set; }
        public Nullable<byte> GstServiceTypeId { get; set; }
        public Nullable<bool> IsRcm { get; set; }
        public Nullable<bool> IsInterState { get; set; }
        public Nullable<decimal> GstRate { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TaxTotal { get; set; }
        public byte TdsGroupId { get; set; }
        public short TdsAccountId { get; set; }
        public decimal TdsRate { get; set; }
        public decimal TdsAmount { get; set; }
        public decimal OtherDeduction { get; set; }
        public decimal DiscountReceived { get; set; }
        public decimal GrandTotal { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal PendAmount { get; set; }
        public bool IsCancel { get; set; }
        public short CancelBy { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string Remarks { get; set; }
        public string PanNo { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public byte CompanyId { get; set; }
        public Nullable<bool> IsPayment { get; set; }
        public bool IsCostCenterApplicable { get; set; }
        public Nullable<short> CompanyLocationId { get; set; }
        public Nullable<short> VendorLocationId { get; set; }
        public string VendorName { get; set; }
        public Nullable<long> PaymentId { get; set; }
        public string CancelReason { get; set; }
        public Nullable<decimal> ContractAmount { get; set; }
        public Nullable<bool> isCreditDebitNote { get; set; }
        public string VendorGstNo { get; set; }
        public Nullable<short> VendorGstCityId { get; set; }
        public string VendorGstAddress { get; set; }
    
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        public virtual CL_Master_Vendor CL_Master_Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_VendorBill_OtherDetail> CL_VendorBill_OtherDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_VendorBill_Charge_Detail> CL_VendorBill_Charge_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_VendorBill_Detail> CL_VendorBill_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_VendorBill_Tax_Detail> CL_VendorBill_Tax_Detail { get; set; }
    }
}
