//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Voucher_AccountDetail
    {
        public long VoucherId { get; set; }
        public bool IsGstExempted { get; set; }
        public bool IsTdsExempted { get; set; }
        public bool IsProduct { get; set; }
        public short AccountId { get; set; }
        public byte SacId { get; set; }
        public int Units { get; set; }
        public string Narration { get; set; }
        public decimal Amount { get; set; }
        public decimal GstAmount { get; set; }
        public decimal GstCharged { get; set; }
        public decimal TotalAmount { get; set; }
        public byte DocumentTypeId { get; set; }
        public long DocumentId { get; set; }
        public decimal GstRate { get; set; }
        public byte CostCenterType { get; set; }
        public long CostCenterId { get; set; }
    
        public virtual CL_Master_Account CL_Master_Account { get; set; }
        public virtual CL_Voucher_Detail CL_Voucher_Detail { get; set; }
    }
}
