//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_Voucher_Summary
    {
        public long VoucherId { get; set; }
        public byte BusinessTypeId { get; set; }
        public string Remarks { get; set; }
        public string ReferenceNo { get; set; }
        public short AccountingLocationId { get; set; }
        public Nullable<long> CompanyGstId { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Igst { get; set; }
        public decimal Cgst { get; set; }
        public decimal Sgst { get; set; }
        public decimal Ugst { get; set; }
        public decimal TaxTotal { get; set; }
        public short TdsAccountId { get; set; }
        public decimal TdsRate { get; set; }
        public decimal TdsAmount { get; set; }
        public decimal GrandTotal { get; set; }
        public decimal NetAmount { get; set; }
        public byte GstExemptedCategory { get; set; }
        public string DocumentName { get; set; }
        public string VendorInvoiceDocumentName { get; set; }
        public Nullable<long> PartyGstId { get; set; }
        public Nullable<short> PartyStateId { get; set; }
    
        public virtual CL_Master_Gst CL_Master_Gst { get; set; }
        public virtual CL_Master_Location CL_Master_Location { get; set; }
        public virtual CL_Voucher_Detail CL_Voucher_Detail { get; set; }
    }
}
