//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_VehicleStatusHeader
    {
        public short VehicleId { get; set; }
        public int VehicleStatus { get; set; }
        public Nullable<int> StatusReason { get; set; }
        public short EntryBy { get; set; }
        public System.DateTime EntryDateTime { get; set; }
        public string VehLocation { get; set; }
        public Nullable<System.DateTime> VehStatusDateTime { get; set; }
        public string VehRemarks { get; set; }
        public string DriverName { get; set; }
        public string DriverMobNo { get; set; }
        public string SupervisorName { get; set; }
        public string SupervisorMobNo { get; set; }
    }
}
