//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_VendorBill_Charge_Detail
    {
        public long BillId { get; set; }
        public long DocumentId { get; set; }
        public byte DocumentTypeId { get; set; }
        public byte ChargeCode { get; set; }
        public decimal ChargeAmount { get; set; }
    
        public virtual CL_VendorBill_Header CL_VendorBill_Header { get; set; }
    }
}
