//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_VendorBill_OtherDetail
    {
        public long BillId { get; set; }
        public short AccountId { get; set; }
        public bool IsGoodsProduct { get; set; }
        public byte SacId { get; set; }
        public bool GstExempted { get; set; }
        public bool TdsExempted { get; set; }
        public decimal Amount { get; set; }
        public decimal GstAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public string Narration { get; set; }
        public int Units { get; set; }
        public byte CostCenterTypeId { get; set; }
        public long CostCenterId { get; set; }
        public decimal GstRate { get; set; }
    
        public virtual CL_Master_Account CL_Master_Account { get; set; }
        public virtual CL_VendorBill_Header CL_VendorBill_Header { get; set; }
    }
}
