//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_VendorPayment_Detail
    {
        public long PaymentId { get; set; }
        public long DocumentId { get; set; }
        public byte DocumentType { get; set; }
        public decimal Amount { get; set; }
    
        public virtual CL_VendorPayment_Header CL_VendorPayment_Header { get; set; }
    }
}
