//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ewayBill
    {
        public int ID { get; set; }
        public string stateName { get; set; }
        public string GSTIN { get; set; }
        public string EWBUserName { get; set; }
        public string EWBPassword { get; set; }
    }
}
