//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ewayBill
    {
        public int GSTIN { get; set; }
        public string State { get; set; }
        public string EWBUserName { get; set; }
        public string EWBPassword { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public string EFUserName { get; set; }
        public string EFPassword { get; set; }
        public string CDKey { get; set; }
    }
}
