//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAL_Email_Log
    {
        public long pk_emaillogId { get; set; }
        public Nullable<System.DateTime> dated { get; set; }
        public string ProfileName { get; set; }
        public string TOAddress { get; set; }
        public string CCAddress { get; set; }
        public string TOSubject { get; set; }
        public string MailBody { get; set; }
        public string DocumentPath { get; set; }
        public string fk_companyId { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> sent_date { get; set; }
    }
}
