//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_CL_Master_Vehicle
    {
        public short VehicleId { get; set; }
        public string VehicleNo { get; set; }
        public short VehicleTypeId { get; set; }
        public short VendorId { get; set; }
        public byte FtlTypeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public short LocationId { get; set; }
        public Nullable<int> StartKm { get; set; }
        public bool VehicleStatus { get; set; }
    }
}
