//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_CL_Master_City
    {
        public Nullable<short> StateId { get; set; }
        public Nullable<byte> ZoneId { get; set; }
        public int CityId { get; set; }
        public string CityName { get; set; }
        public Nullable<bool> IsPermitRequired { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<short> EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<short> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsOdaApplicable { get; set; }
        public Nullable<decimal> OdaKm { get; set; }
    }
}
