//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUDWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_Master_Vendor
    {
        public Nullable<byte> VendorTypeId { get; set; }
        public short VendorId { get; set; }
        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ContractApplicableId { get; set; }
    }
}
